<?php 
			
	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz
	 */
	 
	namespace src\model; 

	class Contatos {
			
		private $id;
		private $contato;
		private $nome;
		private $email;
		private $celular;
		private $cadastrado;
		private $modificado;
		private $situacao_contato;
			
		public function __construct() { }
			
		public function setId($id) {
			$this->id = $id;
		}
		
		public function getId() {
			return $this->id;
		}
					
		public function setContato($contato) {
			$this->contato = $contato;
		}
		
		public function getContato() {
			return $this->contato;
		}
					
		public function setNome($nome) {
			$this->nome = $nome;
		}
		
		public function getNome() {
			return $this->nome;
		}
					
		public function setEmail($email) {
			$this->email = $email;
		}
		
		public function getEmail() {
			return $this->email;
		}
					
		public function setCelular($celular) {
			$this->celular = $celular;
		}
		
		public function getCelular() {
			return $this->celular;
		}
					
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}
		
		public function getCadastrado() {
			return $this->cadastrado;
		}
					
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}
		
		public function getModificado() {
			return $this->modificado;
		}
					
		public function setSituacao_contato($situacao_contato) {
			$this->situacao_contato = $situacao_contato;
		}
		
		public function getSituacao_contato() {
			return $this->situacao_contato;
		}
					
	}
	
?>