<?php
			
	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz 
	 */
	 
	namespace src\model; 
	
	use src\model;
	
	class ContatosDao {
	
		private $connection;
		
		/*
		 * Constant variables
		 */
		private $create = "INSERT INTO contatos (
				contato
				, nome
				, email
				, celular
				, cadastrado
				, modificado
				, situacao_contato
				) VALUES";
				
		public $read = 
				"contatos.id AS \"contatos.id\"
				, contatos.contato AS \"contatos.contato\"
				, contatos.nome AS \"contatos.nome\"
				, contatos.email AS \"contatos.email\"
				, contatos.celular AS \"contatos.celular\"
				, contatos.cadastrado AS \"contatos.cadastrado\"
				, contatos.modificado AS \"contatos.modificado\"
				, contatos.situacao_contato AS \"contatos.situacao_contato\"
				";
				
		private $update = "UPDATE contatos SET";
		private $delete = "DELETE FROM contatos";
		
		public $from = "contatos contatos";
		
		/*
		 * Parameters
		 */
		private $where;
		private $order;
		
		// Dynamic query
		private $sql;
		
		// Controller response
		private $response;	
		
		/**
		 * @param {Object} connection
		 */
		public function __construct($connection) {
			$this->connection = $connection;
		}

		/**
		 * @param {Contatos}contatos
		 */
		public function setCreate($contatos) {		
			$this->sql = $this->create . " (\"" . 
					$contatos->getContato() .
					"\", \"" . $contatos->getNome() .
					"\", \"" . $contatos->getEmail() .
					"\", \"" . $contatos->getCelular() .
					"\", \"" . $contatos->getCadastrado() .
					"\", \"" . $contatos->getModificado() .
					"\", \"" . $contatos->getSituacao_contato() .
					"\")";
		}
		
		/**
		 * @return {String}
		 */
		public function getCreate() {
			return $this->sql;
		}	
		
		/**
		 * @param {String} where
		 * @param {String} order
		 */
		public function setRead($where, $order) {
			$situacoes_contatosDao = new model\Situacoes_contatosDao($this->connection);
			
			$this->setWhere($where);
			$this->setOrder($order);
			
			$this->sql = "SELECT " . $this->read . ", " . $situacoes_contatosDao->read . 
					" FROM " . $this->getFrom() .", " . $situacoes_contatosDao->from . 
					($this->getWhere() == "" ? " WHERE contatos.situacao_contato = situacoes_contatos.id" : $this->getWhere()) . 
					" AND contatos.situacao_contato = situacoes_contatos.id" . $this->getOrder();
		}
		
		/**
		 * @return {String}
		 */
		public function getRead() {
			return $this->sql;
		}
		
		/**
		 * @param {Contatos}contatos  
		 * @param {String} where
		 */
		public function setUpdate($contatos, $where) {
			$this->setWhere($where);
			
			$this->sql = $this->update . 
					" id = \"" . $contatos->getId() . 
					"\", contato = \"" . $contatos->getContato() . 
					"\", nome = \"" . $contatos->getNome() . 
					"\", email = \"" . $contatos->getEmail() . 
					"\", celular = \"" . $contatos->getCelular() . 
					"\", modificado = \"" . $contatos->getModificado() . 
					"\", situacao_contato = \"" . $contatos->getSituacao_contato() . 
					"\"" . $this->getWhere();
		}
		
		/**
		 * @return {String}
		 */
		public function getUpdate() {
			return $this->sql;
		}
		
		/**
		 * @param {String} where
		 */
		public function setDelete($where) {	
			$this->setWhere($where);
			
			$this->sql = $this->delete . $this->getWhere();
		}
		
		/**
		 * @return {String}
		 */
		public function getDelete() {
			return $this->sql;
		}
		
		/**
		 * @return {String}
		 */
		public function getFrom() {
			return $this->from;
		}
		
		/**
		 * @param {String} where
		 */
		public function setWhere($where) {
			if ($where != "")
				$this->where = " WHERE " . $where;
			else
				$this->where = "";
		}
		
		/**
		 * @return {String}
		 */
		public function getWhere() {
			return $this->where;
		}
		
		/**
		 * @param {String} order
		 */
		public function setOrder($order) {
			if ($order != "")
				$this->order = " ORDER BY " . $order;
			else
				$this->order = "";
		}
		
		/**
		 * @return {String}
		 */
		public function getOrder() {
			return $this->order;
		}
		
		/**
		 * @param {Integer} line
		 * @param column String
		 * @param value String
		 */
		private function setResponse($line, $column, $value) {
			$this->response[$line][$column] = $value;
		}

		/**
		 * @return {Array}
		 */
		private function getResponse() {
			return $this->response;
		}

		/**
		 * @param {String} where
		 */
		private function setSize($where) {
			$this->setWhere($where);
			
			$result = $this->connection->execute(
					"SELECT count(1) AS \"contatos.size\" from contatos" . $this->getWhere());

			while ($row = $result->fetch_assoc()) {		
				$this->setResponse(0, "contatos.size", $row["contatos.size"]);
				
				$pages = ceil($row["contatos.size"] / $this->connection->getItensPerPage());
				
				$this->setResponse(0, "contatos.page", $this->connection->getPosition());
				$this->setResponse(0, "contatos.pages", $pages);
				
				$pagination = "<select id='gz-select-pagination' onchange='goPage();'>";
				
				for ($i = 1; $i <= $pages; $i++) {
					if ($i == $this->connection->getPosition())
						$pagination .= "<option value='" . $i . "' selected>" . $i . "</option>";
					else
						$pagination .= "<option value='" . $i . "'>" . $i . "</option>";
				}	

				$pagination .= "</select>";
						
				$this->setResponse(0, "contatos.pagination", $pagination);
			}

			$this->connection->free($result);
		}
		
		/**
		 * @param {Integer} line
		 */
		public function setDivLine($line) {
			$this->setResponse($line - 1, "@_START_LINE_TWO", modelStartLine($line, 2));
			$this->setResponse($line - 1, "@_END_LINE_TWO", modelEndLine($line, 2));

			$this->setResponse($line - 1, "@_START_LINE_THREE", modelStartLine($line, 3));
			$this->setResponse($line - 1, "@_END_LINE_THREE", modelEndLine($line, 3));
			
			$this->setResponse($line - 1, "@_START_LINE_FOUR", modelStartLine($line, 4));
			$this->setResponse($line - 1, "@_END_LINE_FOUR", modelEndLine($line, 4));
		}
		
		/**
		 * @param {Integer} line
		 */
		public function checkDivLine($line) {
			if (modelCheckEndLine($line, 2) != "")
				$this->setResponse($line - 1, "@_END_LINE_TWO", modelCheckEndLine($line, 2));
			
			if (modelCheckEndLine($line, 3) != "")
				$this->setResponse($line - 1, "@_END_LINE_THREE", modelCheckEndLine($line, 3));		

			if (modelCheckEndLine($line, 4) != "")
				$this->setResponse($line - 1, "@_END_LINE_FOUR", modelCheckEndLine($line, 4));			
		}	

		/**
		 * @param {String} log
		 */
		private function setLog($log) {
			$this->setResponse(0, "log", $log);
		}
		
		/**
		 * @param {Contatos} contatos 
		 * @return {Boolean}
		 */
		public function create($contatos) {
			$result = "";

			$this->setCreate($contatos);
			$result = $this->connection->execute($this->getCreate());
			
			return $result;
		}

		/**
		 * @param {String} where
		 * @param {String} order
		 * @param {Boolean} wp
		 * @param {Array}
		 */
		public function read($where, $order, $wp) {
			$line = 0;

			$this->setRead($where, $order);
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($line, "contatos.id", $row["contatos.id"]);
				$this->setResponse($line, "contatos.contato", $row["contatos.contato"]);
				$this->setResponse($line, "contatos.contato.format", modelDoubleQuotes(modelTextArea($row["contatos.contato"])));
				$this->setResponse($line, "contatos.nome", $row["contatos.nome"]);
				$this->setResponse($line, "contatos.nome.format.json", modelDoubleQuotesJson($row["contatos.nome"]));
				$this->setResponse($line, "contatos.email", $row["contatos.email"]);
				$this->setResponse($line, "contatos.celular", $row["contatos.celular"]);
				$this->setResponse($line, "contatos.cadastrado", modelDateTime($row["contatos.cadastrado"]));
				$this->setResponse($line, "contatos.modificado", modelDateTime($row["contatos.modificado"]));
				$this->setResponse($line, "contatos.situacao_contato", $row["contatos.situacao_contato"]);
				$this->setResponse($line, "situacoes_contatos.situacao_contato", $row["situacoes_contatos.situacao_contato"]);
			
				$this->setResponse($line, "contatos.line", $line);
			
				$line++;
				
				if ($wp)
					$this->setDivLine($line);
			}

			$this->connection->free($result);
			
			if ($wp && $line > 0) {
				$this->checkDivLine($line);
				
				$this->setSize($where);
			}

			return $this->getResponse();
		}

		/**
		 * @param {Contatos} contatos 
		 * @return {Boolean}
		 */
		public function update($contatos) {
			$result = "";
			
			$this->setUpdate($contatos, "contatos.id = " . $contatos->getId());
			$result = $this->connection->execute($this->getUpdate());

			return $result;
		}

		/**
		 * @param {String} where
		 * @return {Boolean}
		 */
		public function delete($where) {
			$result = "";
			
			$this->setDelete($where);
			$result = $this->connection->execute($this->getDelete());

			return $result;
		}
		
		/**
		 * @param {Integer} selected
		 * @param {String} order
		 * @return {Array}
		 */
		public function combo($selected, $order) {
			$size = 0;

			$this->setRead("", $order);
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($size, "contatos.id", $row["contatos.id"]);
				$this->setResponse($size, "contatos.contato", $row["contatos.contato"]);
			
				if ($row["contatos.id"] == $selected)
					$this->setResponse($size, "contatos.selected", "selected");
				else
					$this->setResponse($size, "contatos.selected", "");
					
				$size++;
			}
			
			$this->connection->free($result);
			
			$this->setResponse(0, "size", $size);

			return $this->getResponse();
		}
		
		/**
		 * @param {String} where
		 * @return {Array}
		 */
		public function comboScr($where) {
			$size = 0;

			$this->setRead($where, "");
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($size, "contatos.id", $row["contatos.id"]);
				$this->setResponse($size, "contatos.contato", $row["contatos.contato"]);
				$this->setResponse($size, "contatos.selected", "selected");
					
				$size++;
			}
			
			$this->connection->free($result);
			
			$this->setResponse(0, "size", $size);

			return $this->getResponse();
		}

	}

?>