<?php 
			
	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz
	 */
	 
	namespace src\model; 

	class Elementos {
			
		private $id;
		private $elemento;
		private $ordem;
		private $cadastrado;
		private $modificado;
		private $tipo_linha;
		private $tipo_coluna;
		private $situacao_registro;
		private $cor;
			
		public function __construct() { }
			
		public function setId($id) {
			$this->id = $id;
		}
		
		public function getId() {
			return $this->id;
		}
					
		public function setElemento($elemento) {
			$this->elemento = $elemento;
		}
		
		public function getElemento() {
			return $this->elemento;
		}
					
		public function setOrdem($ordem) {
			$this->ordem = $ordem;
		}
		
		public function getOrdem() {
			return $this->ordem;
		}
					
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}
		
		public function getCadastrado() {
			return $this->cadastrado;
		}
					
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}
		
		public function getModificado() {
			return $this->modificado;
		}
					
		public function setTipo_linha($tipo_linha) {
			$this->tipo_linha = $tipo_linha;
		}
		
		public function getTipo_linha() {
			return $this->tipo_linha;
		}
					
		public function setTipo_coluna($tipo_coluna) {
			$this->tipo_coluna = $tipo_coluna;
		}
		
		public function getTipo_coluna() {
			return $this->tipo_coluna;
		}
					
		public function setSituacao_registro($situacao_registro) {
			$this->situacao_registro = $situacao_registro;
		}
		
		public function getSituacao_registro() {
			return $this->situacao_registro;
		}
					
		public function setCor($cor) {
			$this->cor = $cor;
		}
		
		public function getCor() {
			return $this->cor;
		}
					
	}
	
?>