<?php
			
	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz 
	 */
	 
	namespace src\model; 
	
	use src\model;
	
	class ElementosDao {
	
		private $connection;
		
		/*
		 * Constant variables
		 */
		private $create = "INSERT INTO elementos (
				elemento
				, ordem
				, cadastrado
				, modificado
				, tipo_linha
				, tipo_coluna
				, situacao_registro
				, cor
				) VALUES";
				
		public $read = 
				"elementos.id AS \"elementos.id\"
				, elementos.elemento AS \"elementos.elemento\"
				, elementos.ordem AS \"elementos.ordem\"
				, elementos.cadastrado AS \"elementos.cadastrado\"
				, elementos.modificado AS \"elementos.modificado\"
				, elementos.tipo_linha AS \"elementos.tipo_linha\"
				, elementos.tipo_coluna AS \"elementos.tipo_coluna\"
				, elementos.situacao_registro AS \"elementos.situacao_registro\"
				, elementos.cor AS \"elementos.cor\"
				";
				
		private $update = "UPDATE elementos SET";
		private $delete = "DELETE FROM elementos";
		
		public $from = "elementos elementos";
		
		/*
		 * Parameters
		 */
		private $where;
		private $order;
		
		// Dynamic query
		private $sql;
		
		// Controller response
		private $response;	
		
		/**
		 * @param {Object} connection
		 */
		public function __construct($connection) {
			$this->connection = $connection;
		}

		/**
		 * @param {Elementos}elementos
		 */
		public function setCreate($elementos) {		
			$this->sql = $this->create . " (\"" . 
					$elementos->getElemento() .
					"\", \"" . $elementos->getOrdem() .
					"\", \"" . $elementos->getCadastrado() .
					"\", \"" . $elementos->getModificado() .
					"\", \"" . $elementos->getTipo_linha() .
					"\", \"" . $elementos->getTipo_coluna() .
					"\", \"" . $elementos->getSituacao_registro() .
					"\", \"" . $elementos->getCor() .
					"\")";
		}
		
		/**
		 * @return {String}
		 */
		public function getCreate() {
			return $this->sql;
		}	
		
		/**
		 * @param {String} where
		 * @param {String} order
		 */
		public function setRead($where, $order) {
			$tipos_linhasDao = new model\Tipos_linhasDao($this->connection);
			$tipos_colunasDao = new model\Tipos_colunasDao($this->connection);
			$situacoes_registrosDao = new model\Situacoes_registrosDao($this->connection);
			$coresDao = new model\CoresDao($this->connection);
			
			$this->setWhere($where);
			$this->setOrder($order);
			
			$this->sql = "SELECT " . $this->read . ", " . $tipos_linhasDao->read . ", " . $tipos_colunasDao->read . ", " . $situacoes_registrosDao->read . ", " . $coresDao->read . 
					" FROM " . $this->getFrom() .", " . $tipos_linhasDao->from . ", " . $tipos_colunasDao->from . ", " . $situacoes_registrosDao->from . ", " . $coresDao->from . 
					($this->getWhere() == "" ? " WHERE elementos.tipo_linha = tipos_linhas.id AND elementos.tipo_coluna = tipos_colunas.id AND elementos.situacao_registro = situacoes_registros.id AND elementos.cor = cores.id" : $this->getWhere()) . 
					" AND elementos.tipo_linha = tipos_linhas.id AND elementos.tipo_coluna = tipos_colunas.id AND elementos.situacao_registro = situacoes_registros.id AND elementos.cor = cores.id" . $this->getOrder();
		}
		
		/**
		 * @return {String}
		 */
		public function getRead() {
			return $this->sql;
		}
		
		/**
		 * @param {Elementos}elementos  
		 * @param {String} where
		 */
		public function setUpdate($elementos, $where) {
			$this->setWhere($where);
			
			$this->sql = $this->update . 
					" id = \"" . $elementos->getId() . 
					"\", elemento = \"" . $elementos->getElemento() . 
					"\", ordem = \"" . $elementos->getOrdem() . 
					"\", modificado = \"" . $elementos->getModificado() . 
					"\", tipo_linha = \"" . $elementos->getTipo_linha() . 
					"\", tipo_coluna = \"" . $elementos->getTipo_coluna() . 
					"\", situacao_registro = \"" . $elementos->getSituacao_registro() . 
					"\", cor = \"" . $elementos->getCor() . 
					"\"" . $this->getWhere();
		}
		
		/**
		 * @return {String}
		 */
		public function getUpdate() {
			return $this->sql;
		}
		
		/**
		 * @param {String} where
		 */
		public function setDelete($where) {	
			$this->setWhere($where);
			
			$this->sql = $this->delete . $this->getWhere();
		}
		
		/**
		 * @return {String}
		 */
		public function getDelete() {
			return $this->sql;
		}
		
		/**
		 * @return {String}
		 */
		public function getFrom() {
			return $this->from;
		}
		
		/**
		 * @param {String} where
		 */
		public function setWhere($where) {
			if ($where != "")
				$this->where = " WHERE " . $where;
			else
				$this->where = "";
		}
		
		/**
		 * @return {String}
		 */
		public function getWhere() {
			return $this->where;
		}
		
		/**
		 * @param {String} order
		 */
		public function setOrder($order) {
			if ($order != "")
				$this->order = " ORDER BY " . $order;
			else
				$this->order = "";
		}
		
		/**
		 * @return {String}
		 */
		public function getOrder() {
			return $this->order;
		}
		
		/**
		 * @param {Integer} line
		 * @param column String
		 * @param value String
		 */
		private function setResponse($line, $column, $value) {
			$this->response[$line][$column] = $value;
		}

		/**
		 * @return {Array}
		 */
		private function getResponse() {
			return $this->response;
		}

		/**
		 * @param {String} where
		 */
		private function setSize($where) {
			$this->setWhere($where);
			
			$result = $this->connection->execute(
					"SELECT count(1) AS \"elementos.size\" from elementos" . $this->getWhere());

			while ($row = $result->fetch_assoc()) {		
				$this->setResponse(0, "elementos.size", $row["elementos.size"]);
				
				$pages = ceil($row["elementos.size"] / $this->connection->getItensPerPage());
				
				$this->setResponse(0, "elementos.page", $this->connection->getPosition());
				$this->setResponse(0, "elementos.pages", $pages);
				
				$pagination = "<select id='gz-select-pagination' onchange='goPage();'>";
				
				for ($i = 1; $i <= $pages; $i++) {
					if ($i == $this->connection->getPosition())
						$pagination .= "<option value='" . $i . "' selected>" . $i . "</option>";
					else
						$pagination .= "<option value='" . $i . "'>" . $i . "</option>";
				}	

				$pagination .= "</select>";
						
				$this->setResponse(0, "elementos.pagination", $pagination);
			}

			$this->connection->free($result);
		}
		
		/**
		 * @param {Integer} line
		 */
		public function setDivLine($line) {
			$this->setResponse($line - 1, "@_START_LINE_TWO", modelStartLine($line, 2));
			$this->setResponse($line - 1, "@_END_LINE_TWO", modelEndLine($line, 2));

			$this->setResponse($line - 1, "@_START_LINE_THREE", modelStartLine($line, 3));
			$this->setResponse($line - 1, "@_END_LINE_THREE", modelEndLine($line, 3));
			
			$this->setResponse($line - 1, "@_START_LINE_FOUR", modelStartLine($line, 4));
			$this->setResponse($line - 1, "@_END_LINE_FOUR", modelEndLine($line, 4));
		}
		
		/**
		 * @param {Integer} line
		 */
		public function checkDivLine($line) {
			if (modelCheckEndLine($line, 2) != "")
				$this->setResponse($line - 1, "@_END_LINE_TWO", modelCheckEndLine($line, 2));
			
			if (modelCheckEndLine($line, 3) != "")
				$this->setResponse($line - 1, "@_END_LINE_THREE", modelCheckEndLine($line, 3));		

			if (modelCheckEndLine($line, 4) != "")
				$this->setResponse($line - 1, "@_END_LINE_FOUR", modelCheckEndLine($line, 4));			
		}	

		/**
		 * @param {String} log
		 */
		private function setLog($log) {
			$this->setResponse(0, "log", $log);
		}
		
		/**
		 * @param {Elementos} elementos 
		 * @return {Boolean}
		 */
		public function create($elementos) {
			$result = "";

			$this->setCreate($elementos);
			$result = $this->connection->execute($this->getCreate());
			
			return $result;
		}

		/**
		 * @param {String} where
		 * @param {String} order
		 * @param {Boolean} wp
		 * @param {Array}
		 */
		public function read($where, $order, $wp) {
			$line = 0;

			$this->setRead($where, $order);
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($line, "elementos.id", $row["elementos.id"]);
				$this->setResponse($line, "elementos.elemento", $row["elementos.elemento"]);
				$this->setResponse($line, "elementos.elemento.format.json", modelDoubleQuotesJson($row["elementos.elemento"]));
				$this->setResponse($line, "elementos.elemento.format", modelDoubleQuotes($row["elementos.elemento"]));
				$this->setResponse($line, "elementos.elemento.view", addLine($row["elementos.elemento"]));
				$this->setResponse($line, "elementos.ordem", $row["elementos.ordem"]);
				$this->setResponse($line, "elementos.cadastrado", modelDateTime($row["elementos.cadastrado"]));
				$this->setResponse($line, "elementos.modificado", modelDateTime($row["elementos.modificado"]));
				$this->setResponse($line, "elementos.tipo_linha", $row["elementos.tipo_linha"]);
				$this->setResponse($line, "tipos_linhas.tipo_linha", $row["tipos_linhas.tipo_linha"]);
				$this->setResponse($line, "elementos.tipo_coluna", $row["elementos.tipo_coluna"]);
				$this->setResponse($line, "tipos_colunas.tipo_coluna", $row["tipos_colunas.tipo_coluna"]);
				$this->setResponse($line, "elementos.situacao_registro", $row["elementos.situacao_registro"]);
				$this->setResponse($line, "situacoes_registros.situacao_registro", $row["situacoes_registros.situacao_registro"]);
				$this->setResponse($line, "elementos.cor", $row["elementos.cor"]);
				$this->setResponse($line, "cores.cor", $row["cores.cor"]);
			
				$this->setResponse($line, "elementos.line", $line);
			
				$line++;
				
				if ($wp)
					$this->setDivLine($line);
			}

			$this->connection->free($result);
			
			if ($wp && $line > 0) {
				$this->checkDivLine($line);
				
				$this->setSize($where);
			}

			return $this->getResponse();
		}

		/**
		 * @param {Elementos} elementos 
		 * @return {Boolean}
		 */
		public function update($elementos) {
			$result = "";
			
			$this->setUpdate($elementos, "elementos.id = " . $elementos->getId());
			$result = $this->connection->execute($this->getUpdate());

			return $result;
		}

		/**
		 * @param {String} where
		 * @return {Boolean}
		 */
		public function delete($where) {
			$result = "";
			
			$this->setDelete($where);
			$result = $this->connection->execute($this->getDelete());

			return $result;
		}
		
		/**
		 * @param {Integer} selected
		 * @param {String} order
		 * @return {Array}
		 */
		public function combo($selected, $order) {
			$size = 0;

			$this->setRead("", $order);
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($size, "elementos.id", $row["elementos.id"]);
				$this->setResponse($size, "elementos.elemento", $row["elementos.elemento"]);
			
				if ($row["elementos.id"] == $selected)
					$this->setResponse($size, "elementos.selected", "selected");
				else
					$this->setResponse($size, "elementos.selected", "");
					
				$size++;
			}
			
			$this->connection->free($result);
			
			$this->setResponse(0, "size", $size);

			return $this->getResponse();
		}
		
		/**
		 * @param {String} where
		 * @return {Array}
		 */
		public function comboScr($where) {
			$size = 0;

			$this->setRead($where, "");
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($size, "elementos.id", $row["elementos.id"]);
				$this->setResponse($size, "elementos.elemento", $row["elementos.elemento"]);
				$this->setResponse($size, "elementos.selected", "selected");
					
				$size++;
			}
			
			$this->connection->free($result);
			
			$this->setResponse(0, "size", $size);

			return $this->getResponse();
		}

	}

?>