<?php 
			
	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz
	 */
	 
	namespace src\model; 

	class Elemento_conteudos {
			
		private $id;
		private $elemento_conteudo;
		private $ordem;
		private $cadastrado;
		private $modificado;
		private $elemento;
		private $situacao_registro;
		private $tipo_alinhamento_horizontal;
		private $tipo_alinhamento_vertical;
			
		public function __construct() { }
			
		public function setId($id) {
			$this->id = $id;
		}
		
		public function getId() {
			return $this->id;
		}
					
		public function setElemento_conteudo($elemento_conteudo) {
			$this->elemento_conteudo = $elemento_conteudo;
		}
		
		public function getElemento_conteudo() {
			return $this->elemento_conteudo;
		}
					
		public function setOrdem($ordem) {
			$this->ordem = $ordem;
		}
		
		public function getOrdem() {
			return $this->ordem;
		}
					
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}
		
		public function getCadastrado() {
			return $this->cadastrado;
		}
					
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}
		
		public function getModificado() {
			return $this->modificado;
		}
					
		public function setElemento($elemento) {
			$this->elemento = $elemento;
		}
		
		public function getElemento() {
			return $this->elemento;
		}
					
		public function setSituacao_registro($situacao_registro) {
			$this->situacao_registro = $situacao_registro;
		}
		
		public function getSituacao_registro() {
			return $this->situacao_registro;
		}
					
		public function setTipo_alinhamento_horizontal($tipo_alinhamento_horizontal) {
			$this->tipo_alinhamento_horizontal = $tipo_alinhamento_horizontal;
		}
		
		public function getTipo_alinhamento_horizontal() {
			return $this->tipo_alinhamento_horizontal;
		}
					
		public function setTipo_alinhamento_vertical($tipo_alinhamento_vertical) {
			$this->tipo_alinhamento_vertical = $tipo_alinhamento_vertical;
		}
		
		public function getTipo_alinhamento_vertical() {
			return $this->tipo_alinhamento_vertical;
		}
					
	}
	
?>