<?php
			
	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz 
	 */
	 
	namespace src\model; 
	
	use src\model;
	
	class NoticiasDao {
	
		private $connection;
		
		/*
		 * Constant variables
		 */
		private $create = "INSERT INTO noticias (
				noticia
				, foto
				, legenda_foto
				, resumo
				, conteudo
				, palavras_chaves
				, cadastrado
				, modificado
				, usuario
				, situacao_registro
				, tipo_noticia
				) VALUES";
				
		public $read = 
				"noticias.id AS \"noticias.id\"
				, noticias.noticia AS \"noticias.noticia\"
				, noticias.foto AS \"noticias.foto\"
				, noticias.legenda_foto AS \"noticias.legenda_foto\"
				, noticias.resumo AS \"noticias.resumo\"
				, noticias.conteudo AS \"noticias.conteudo\"
				, noticias.palavras_chaves AS \"noticias.palavras_chaves\"
				, noticias.cadastrado AS \"noticias.cadastrado\"
				, noticias.modificado AS \"noticias.modificado\"
				, noticias.usuario AS \"noticias.usuario\"
				, noticias.situacao_registro AS \"noticias.situacao_registro\"
				, noticias.tipo_noticia AS \"noticias.tipo_noticia\"
				";
				
		private $update = "UPDATE noticias SET";
		private $delete = "DELETE FROM noticias";
		
		public $from = "noticias noticias";
		
		/*
		 * Parameters
		 */
		private $where;
		private $order;
		
		// Dynamic query
		private $sql;
		
		// Controller response
		private $response;	
		
		/**
		 * @param {Object} connection
		 */
		public function __construct($connection) {
			$this->connection = $connection;
		}

		/**
		 * @param {Noticias}noticias
		 */
		public function setCreate($noticias) {		
			$this->sql = $this->create . " (\"" . 
					$noticias->getNoticia() .
					"\", \"" . $noticias->getFoto() .
					"\", \"" . $noticias->getLegenda_foto() .
					"\", \"" . $noticias->getResumo() .
					"\", \"" . $noticias->getConteudo() .
					"\", \"" . $noticias->getPalavras_chaves() .
					"\", \"" . $noticias->getCadastrado() .
					"\", \"" . $noticias->getModificado() .
					"\", \"" . $noticias->getUsuario() .
					"\", \"" . $noticias->getSituacao_registro() .
					"\", \"" . $noticias->getTipo_noticia() .
					"\")";
		}
		
		/**
		 * @return {String}
		 */
		public function getCreate() {
			return $this->sql;
		}	
		
		/**
		 * @param {String} where
		 * @param {String} order
		 */
		public function setRead($where, $order) {
			$usuariosDao = new model\UsuariosDao($this->connection);
			$situacoes_registrosDao = new model\Situacoes_registrosDao($this->connection);
			$tipos_noticiasDao = new model\Tipos_noticiasDao($this->connection);
			
			$this->setWhere($where);
			$this->setOrder($order);
			
			$this->sql = "SELECT " . $this->read . ", " . $usuariosDao->read . ", " . $situacoes_registrosDao->read . ", " . $tipos_noticiasDao->read . 
					" FROM " . $this->getFrom() .", " . $usuariosDao->from . ", " . $situacoes_registrosDao->from . ", " . $tipos_noticiasDao->from . 
					($this->getWhere() == "" ? " WHERE noticias.usuario = usuarios.id AND noticias.situacao_registro = situacoes_registros.id AND noticias.tipo_noticia = tipos_noticias.id" : $this->getWhere()) . 
					" AND noticias.usuario = usuarios.id AND noticias.situacao_registro = situacoes_registros.id AND noticias.tipo_noticia = tipos_noticias.id" . $this->getOrder();
		}
		
		/**
		 * @return {String}
		 */
		public function getRead() {
			return $this->sql;
		}
		
		/**
		 * @param {Noticias}noticias  
		 * @param {String} where
		 */
		public function setUpdate($noticias, $where) {
			$this->setWhere($where);
			
			$this->sql = $this->update . 
					" id = \"" . $noticias->getId() . 
					"\", noticia = \"" . $noticias->getNoticia() . 
					"\", foto = \"" . $noticias->getFoto() . 
					"\", legenda_foto = \"" . $noticias->getLegenda_foto() . 
					"\", resumo = \"" . $noticias->getResumo() . 
					"\", conteudo = \"" . $noticias->getConteudo() . 
					"\", palavras_chaves = \"" . $noticias->getPalavras_chaves() . 
					"\", modificado = \"" . $noticias->getModificado() . 
					"\", usuario = \"" . $noticias->getUsuario() . 
					"\", situacao_registro = \"" . $noticias->getSituacao_registro() . 
					"\", tipo_noticia = \"" . $noticias->getTipo_noticia() . 
					"\"" . $this->getWhere();
		}
		
		/**
		 * @return {String}
		 */
		public function getUpdate() {
			return $this->sql;
		}
		
		/**
		 * @param {String} where
		 */
		public function setDelete($where) {	
			$this->setWhere($where);
			
			$this->sql = $this->delete . $this->getWhere();
		}
		
		/**
		 * @return {String}
		 */
		public function getDelete() {
			return $this->sql;
		}
		
		/**
		 * @return {String}
		 */
		public function getFrom() {
			return $this->from;
		}
		
		/**
		 * @param {String} where
		 */
		public function setWhere($where) {
			if ($where != "")
				$this->where = " WHERE " . $where;
			else
				$this->where = "";
		}
		
		/**
		 * @return {String}
		 */
		public function getWhere() {
			return $this->where;
		}
		
		/**
		 * @param {String} order
		 */
		public function setOrder($order) {
			if ($order != "")
				$this->order = " ORDER BY " . $order;
			else
				$this->order = "";
		}
		
		/**
		 * @return {String}
		 */
		public function getOrder() {
			return $this->order;
		}
		
		/**
		 * @param {Integer} line
		 * @param column String
		 * @param value String
		 */
		private function setResponse($line, $column, $value) {
			$this->response[$line][$column] = $value;
		}

		/**
		 * @return {Array}
		 */
		private function getResponse() {
			return $this->response;
		}

		/**
		 * @param {String} where
		 */
		private function setSize($where) {
			$this->setWhere($where);
			
			$result = $this->connection->execute(
					"SELECT count(1) AS \"noticias.size\" from noticias" . $this->getWhere());

			while ($row = $result->fetch_assoc()) {		
				$this->setResponse(0, "noticias.size", $row["noticias.size"]);
				
				$pages = ceil($row["noticias.size"] / $this->connection->getItensPerPage());
				
				$this->setResponse(0, "noticias.page", $this->connection->getPosition());
				$this->setResponse(0, "noticias.pages", $pages);
				
				$pagination = "<select id='gz-select-pagination' onchange='goPage();'>";
				
				for ($i = 1; $i <= $pages; $i++) {
					if ($i == $this->connection->getPosition())
						$pagination .= "<option value='" . $i . "' selected>" . $i . "</option>";
					else
						$pagination .= "<option value='" . $i . "'>" . $i . "</option>";
				}	

				$pagination .= "</select>";
						
				$this->setResponse(0, "noticias.pagination", $pagination);
			}

			$this->connection->free($result);
		}
		
		/**
		 * @param {Integer} line
		 */
		public function setDivLine($line) {
			$this->setResponse($line - 1, "@_START_LINE_TWO", modelStartLine($line, 2));
			$this->setResponse($line - 1, "@_END_LINE_TWO", modelEndLine($line, 2));

			$this->setResponse($line - 1, "@_START_LINE_THREE", modelStartLine($line, 3));
			$this->setResponse($line - 1, "@_END_LINE_THREE", modelEndLine($line, 3));
			
			$this->setResponse($line - 1, "@_START_LINE_FOUR", modelStartLine($line, 4));
			$this->setResponse($line - 1, "@_END_LINE_FOUR", modelEndLine($line, 4));
		}
		
		/**
		 * @param {Integer} line
		 */
		public function checkDivLine($line) {
			if (modelCheckEndLine($line, 2) != "")
				$this->setResponse($line - 1, "@_END_LINE_TWO", modelCheckEndLine($line, 2));
			
			if (modelCheckEndLine($line, 3) != "")
				$this->setResponse($line - 1, "@_END_LINE_THREE", modelCheckEndLine($line, 3));		

			if (modelCheckEndLine($line, 4) != "")
				$this->setResponse($line - 1, "@_END_LINE_FOUR", modelCheckEndLine($line, 4));			
		}	

		/**
		 * @param {String} log
		 */
		private function setLog($log) {
			$this->setResponse(0, "log", $log);
		}
		
		/**
		 * @param {Noticias} noticias 
		 * @return {Boolean}
		 */
		public function create($noticias) {
			$result = "";

			$this->setCreate($noticias);
			$result = $this->connection->execute($this->getCreate());
			
			return $result;
		}

		/**
		 * @param {String} where
		 * @param {String} order
		 * @param {Boolean} wp
		 * @param {Array}
		 */
		public function read($where, $order, $wp) {
			$line = 0;

			$this->setRead($where, $order);
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($line, "noticias.id", $row["noticias.id"]);
				$this->setResponse($line, "noticias.noticia", $row["noticias.noticia"]);
				$this->setResponse($line, "noticias.noticia.format.json", modelDoubleQuotesJson($row["noticias.noticia"]));
				$this->setResponse($line, "noticias.noticia.format", modelDoubleQuotes($row["noticias.noticia"]));
				$this->setResponse($line, "noticias.noticia.view", addLine($row["noticias.noticia"]));
				$this->setResponse($line, "noticias.foto", $row["noticias.foto"]);
				$this->setResponse($line, "noticias.legenda_foto", $row["noticias.legenda_foto"]);
				$this->setResponse($line, "noticias.legenda_foto.format.json", modelDoubleQuotesJson($row["noticias.legenda_foto"]));
				$this->setResponse($line, "noticias.resumo", $row["noticias.resumo"]);
				$this->setResponse($line, "noticias.resumo.format", modelDoubleQuotes(modelTextArea($row["noticias.resumo"])));
				$this->setResponse($line, "noticias.conteudo", $row["noticias.conteudo"]);
				$this->setResponse($line, "noticias.conteudo.format", modelDoubleQuotes(modelTextArea($row["noticias.conteudo"])));
				$this->setResponse($line, "noticias.palavras_chaves", $row["noticias.palavras_chaves"]);
				$this->setResponse($line, "noticias.palavras_chaves.format.json", modelDoubleQuotesJson($row["noticias.palavras_chaves"]));
				$this->setResponse($line, "noticias.cadastrado", modelDateTime($row["noticias.cadastrado"]));
				$this->setResponse($line, "noticias.modificado", modelDateTime($row["noticias.modificado"]));
				$this->setResponse($line, "noticias.usuario", $row["noticias.usuario"]);
				$this->setResponse($line, "usuarios.usuario", $row["usuarios.usuario"]);
				$this->setResponse($line, "noticias.situacao_registro", $row["noticias.situacao_registro"]);
				$this->setResponse($line, "situacoes_registros.situacao_registro", $row["situacoes_registros.situacao_registro"]);
				$this->setResponse($line, "noticias.tipo_noticia", $row["noticias.tipo_noticia"]);
				$this->setResponse($line, "tipos_noticias.tipo_noticia", $row["tipos_noticias.tipo_noticia"]);
			
				$this->setResponse($line, "noticias.line", $line);
			
				$line++;
				
				if ($wp)
					$this->setDivLine($line);
			}

			$this->connection->free($result);
			
			if ($wp && $line > 0) {
				$this->checkDivLine($line);
				
				$this->setSize($where);
			}

			return $this->getResponse();
		}

		/**
		 * @param {Noticias} noticias 
		 * @return {Boolean}
		 */
		public function update($noticias) {
			$result = "";
			
			$this->setUpdate($noticias, "noticias.id = " . $noticias->getId());
			$result = $this->connection->execute($this->getUpdate());

			return $result;
		}

		/**
		 * @param {String} where
		 * @return {Boolean}
		 */
		public function delete($where) {
			$result = "";
			
			$this->setDelete($where);
			$result = $this->connection->execute($this->getDelete());

			return $result;
		}
		
		/**
		 * @param {Integer} selected
		 * @param {String} order
		 * @return {Array}
		 */
		public function combo($selected, $order) {
			$size = 0;

			$this->setRead("", $order);
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($size, "noticias.id", $row["noticias.id"]);
				$this->setResponse($size, "noticias.noticia", $row["noticias.noticia"]);
			
				if ($row["noticias.id"] == $selected)
					$this->setResponse($size, "noticias.selected", "selected");
				else
					$this->setResponse($size, "noticias.selected", "");
					
				$size++;
			}
			
			$this->connection->free($result);
			
			$this->setResponse(0, "size", $size);

			return $this->getResponse();
		}
		
		/**
		 * @param {String} where
		 * @return {Array}
		 */
		public function comboScr($where) {
			$size = 0;

			$this->setRead($where, "");
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($size, "noticias.id", $row["noticias.id"]);
				$this->setResponse($size, "noticias.noticia", $row["noticias.noticia"]);
				$this->setResponse($size, "noticias.selected", "selected");
					
				$size++;
			}
			
			$this->connection->free($result);
			
			$this->setResponse(0, "size", $size);

			return $this->getResponse();
		}

	}

?>