<?php 
			
	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz
	 */
	 
	namespace src\model; 

	class Paginas {
			
		private $id;
		private $pagina;
		private $conteudo;
		private $palavras_chaves;
		private $cadastrado;
		private $modificado;
		private $situacao_registro;
			
		public function __construct() { }
			
		public function setId($id) {
			$this->id = $id;
		}
		
		public function getId() {
			return $this->id;
		}
					
		public function setPagina($pagina) {
			$this->pagina = $pagina;
		}
		
		public function getPagina() {
			return $this->pagina;
		}
					
		public function setConteudo($conteudo) {
			$this->conteudo = $conteudo;
		}
		
		public function getConteudo() {
			return $this->conteudo;
		}
					
		public function setPalavras_chaves($palavras_chaves) {
			$this->palavras_chaves = $palavras_chaves;
		}
		
		public function getPalavras_chaves() {
			return $this->palavras_chaves;
		}
					
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}
		
		public function getCadastrado() {
			return $this->cadastrado;
		}
					
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}
		
		public function getModificado() {
			return $this->modificado;
		}
					
		public function setSituacao_registro($situacao_registro) {
			$this->situacao_registro = $situacao_registro;
		}
		
		public function getSituacao_registro() {
			return $this->situacao_registro;
		}
					
	}
	
?>