<?php
			
	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz 
	 */
	 
	namespace src\model; 
	
	use src\model;
	
	class Situacoes_contatosDao {
	
		private $connection;
		
		/*
		 * Constant variables
		 */
		private $create = "INSERT INTO situacoes_contatos (
				situacao_contato
				, cadastrado
				, modificado
				, cor
				) VALUES";
				
		public $read = 
				"situacoes_contatos.id AS \"situacoes_contatos.id\"
				, situacoes_contatos.situacao_contato AS \"situacoes_contatos.situacao_contato\"
				, situacoes_contatos.cadastrado AS \"situacoes_contatos.cadastrado\"
				, situacoes_contatos.modificado AS \"situacoes_contatos.modificado\"
				, situacoes_contatos.cor AS \"situacoes_contatos.cor\"
				";
				
		private $update = "UPDATE situacoes_contatos SET";
		private $delete = "DELETE FROM situacoes_contatos";
		
		public $from = "situacoes_contatos situacoes_contatos";
		
		/*
		 * Parameters
		 */
		private $where;
		private $order;
		
		// Dynamic query
		private $sql;
		
		// Controller response
		private $response;	
		
		/**
		 * @param {Object} connection
		 */
		public function __construct($connection) {
			$this->connection = $connection;
		}

		/**
		 * @param {Situacoes_contatos}situacoes_contatos
		 */
		public function setCreate($situacoes_contatos) {		
			$this->sql = $this->create . " (\"" . 
					$situacoes_contatos->getSituacao_contato() .
					"\", \"" . $situacoes_contatos->getCadastrado() .
					"\", \"" . $situacoes_contatos->getModificado() .
					"\", \"" . $situacoes_contatos->getCor() .
					"\")";
		}
		
		/**
		 * @return {String}
		 */
		public function getCreate() {
			return $this->sql;
		}	
		
		/**
		 * @param {String} where
		 * @param {String} order
		 */
		public function setRead($where, $order) {
			$coresDao = new model\CoresDao($this->connection);
			
			$this->setWhere($where);
			$this->setOrder($order);
			
			$this->sql = "SELECT " . $this->read . ", " . $coresDao->read . 
					" FROM " . $this->getFrom() .", " . $coresDao->from . 
					($this->getWhere() == "" ? " WHERE situacoes_contatos.cor = cores.id" : $this->getWhere()) . 
					" AND situacoes_contatos.cor = cores.id" . $this->getOrder();
		}
		
		/**
		 * @return {String}
		 */
		public function getRead() {
			return $this->sql;
		}
		
		/**
		 * @param {Situacoes_contatos}situacoes_contatos  
		 * @param {String} where
		 */
		public function setUpdate($situacoes_contatos, $where) {
			$this->setWhere($where);
			
			$this->sql = $this->update . 
					" id = \"" . $situacoes_contatos->getId() . 
					"\", situacao_contato = \"" . $situacoes_contatos->getSituacao_contato() . 
					"\", modificado = \"" . $situacoes_contatos->getModificado() . 
					"\", cor = \"" . $situacoes_contatos->getCor() . 
					"\"" . $this->getWhere();
		}
		
		/**
		 * @return {String}
		 */
		public function getUpdate() {
			return $this->sql;
		}
		
		/**
		 * @param {String} where
		 */
		public function setDelete($where) {	
			$this->setWhere($where);
			
			$this->sql = $this->delete . $this->getWhere();
		}
		
		/**
		 * @return {String}
		 */
		public function getDelete() {
			return $this->sql;
		}
		
		/**
		 * @return {String}
		 */
		public function getFrom() {
			return $this->from;
		}
		
		/**
		 * @param {String} where
		 */
		public function setWhere($where) {
			if ($where != "")
				$this->where = " WHERE " . $where;
			else
				$this->where = "";
		}
		
		/**
		 * @return {String}
		 */
		public function getWhere() {
			return $this->where;
		}
		
		/**
		 * @param {String} order
		 */
		public function setOrder($order) {
			if ($order != "")
				$this->order = " ORDER BY " . $order;
			else
				$this->order = "";
		}
		
		/**
		 * @return {String}
		 */
		public function getOrder() {
			return $this->order;
		}
		
		/**
		 * @param {Integer} line
		 * @param column String
		 * @param value String
		 */
		private function setResponse($line, $column, $value) {
			$this->response[$line][$column] = $value;
		}

		/**
		 * @return {Array}
		 */
		private function getResponse() {
			return $this->response;
		}

		/**
		 * @param {String} where
		 */
		private function setSize($where) {
			$this->setWhere($where);
			
			$result = $this->connection->execute(
					"SELECT count(1) AS \"situacoes_contatos.size\" from situacoes_contatos" . $this->getWhere());

			while ($row = $result->fetch_assoc()) {		
				$this->setResponse(0, "situacoes_contatos.size", $row["situacoes_contatos.size"]);
				
				$pages = ceil($row["situacoes_contatos.size"] / $this->connection->getItensPerPage());
				
				$this->setResponse(0, "situacoes_contatos.page", $this->connection->getPosition());
				$this->setResponse(0, "situacoes_contatos.pages", $pages);
				
				$pagination = "<select id='gz-select-pagination' onchange='goPage();'>";
				
				for ($i = 1; $i <= $pages; $i++) {
					if ($i == $this->connection->getPosition())
						$pagination .= "<option value='" . $i . "' selected>" . $i . "</option>";
					else
						$pagination .= "<option value='" . $i . "'>" . $i . "</option>";
				}	

				$pagination .= "</select>";
						
				$this->setResponse(0, "situacoes_contatos.pagination", $pagination);
			}

			$this->connection->free($result);
		}
		
		/**
		 * @param {Integer} line
		 */
		public function setDivLine($line) {
			$this->setResponse($line - 1, "@_START_LINE_TWO", modelStartLine($line, 2));
			$this->setResponse($line - 1, "@_END_LINE_TWO", modelEndLine($line, 2));

			$this->setResponse($line - 1, "@_START_LINE_THREE", modelStartLine($line, 3));
			$this->setResponse($line - 1, "@_END_LINE_THREE", modelEndLine($line, 3));
			
			$this->setResponse($line - 1, "@_START_LINE_FOUR", modelStartLine($line, 4));
			$this->setResponse($line - 1, "@_END_LINE_FOUR", modelEndLine($line, 4));
		}
		
		/**
		 * @param {Integer} line
		 */
		public function checkDivLine($line) {
			if (modelCheckEndLine($line, 2) != "")
				$this->setResponse($line - 1, "@_END_LINE_TWO", modelCheckEndLine($line, 2));
			
			if (modelCheckEndLine($line, 3) != "")
				$this->setResponse($line - 1, "@_END_LINE_THREE", modelCheckEndLine($line, 3));		

			if (modelCheckEndLine($line, 4) != "")
				$this->setResponse($line - 1, "@_END_LINE_FOUR", modelCheckEndLine($line, 4));			
		}	

		/**
		 * @param {String} log
		 */
		private function setLog($log) {
			$this->setResponse(0, "log", $log);
		}
		
		/**
		 * @param {Situacoes_contatos} situacoes_contatos 
		 * @return {Boolean}
		 */
		public function create($situacoes_contatos) {
			$result = "";

			$this->setCreate($situacoes_contatos);
			$result = $this->connection->execute($this->getCreate());
			
			return $result;
		}

		/**
		 * @param {String} where
		 * @param {String} order
		 * @param {Boolean} wp
		 * @param {Array}
		 */
		public function read($where, $order, $wp) {
			$line = 0;

			$this->setRead($where, $order);
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($line, "situacoes_contatos.id", $row["situacoes_contatos.id"]);
				$this->setResponse($line, "situacoes_contatos.situacao_contato", $row["situacoes_contatos.situacao_contato"]);
				$this->setResponse($line, "situacoes_contatos.situacao_contato.format.json", modelDoubleQuotesJson($row["situacoes_contatos.situacao_contato"]));
				$this->setResponse($line, "situacoes_contatos.situacao_contato.format", modelDoubleQuotes($row["situacoes_contatos.situacao_contato"]));
				$this->setResponse($line, "situacoes_contatos.situacao_contato.view", addLine($row["situacoes_contatos.situacao_contato"]));
				$this->setResponse($line, "situacoes_contatos.cadastrado", modelDateTime($row["situacoes_contatos.cadastrado"]));
				$this->setResponse($line, "situacoes_contatos.modificado", modelDateTime($row["situacoes_contatos.modificado"]));
				$this->setResponse($line, "situacoes_contatos.cor", $row["situacoes_contatos.cor"]);
				$this->setResponse($line, "cores.cor", $row["cores.cor"]);
			
				$this->setResponse($line, "situacoes_contatos.line", $line);
			
				$line++;
				
				if ($wp)
					$this->setDivLine($line);
			}

			$this->connection->free($result);
			
			if ($wp && $line > 0) {
				$this->checkDivLine($line);
				
				$this->setSize($where);
			}

			return $this->getResponse();
		}

		/**
		 * @param {Situacoes_contatos} situacoes_contatos 
		 * @return {Boolean}
		 */
		public function update($situacoes_contatos) {
			$result = "";
			
			$this->setUpdate($situacoes_contatos, "situacoes_contatos.id = " . $situacoes_contatos->getId());
			$result = $this->connection->execute($this->getUpdate());

			return $result;
		}

		/**
		 * @param {String} where
		 * @return {Boolean}
		 */
		public function delete($where) {
			$result = "";
			
			$this->setDelete($where);
			$result = $this->connection->execute($this->getDelete());

			return $result;
		}
		
		/**
		 * @param {Integer} selected
		 * @param {String} order
		 * @return {Array}
		 */
		public function combo($selected, $order) {
			$size = 0;

			$this->setRead("", $order);
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($size, "situacoes_contatos.id", $row["situacoes_contatos.id"]);
				$this->setResponse($size, "situacoes_contatos.situacao_contato", $row["situacoes_contatos.situacao_contato"]);
			
				if ($row["situacoes_contatos.id"] == $selected)
					$this->setResponse($size, "situacoes_contatos.selected", "selected");
				else
					$this->setResponse($size, "situacoes_contatos.selected", "");
					
				$size++;
			}
			
			$this->connection->free($result);
			
			$this->setResponse(0, "size", $size);

			return $this->getResponse();
		}
		
		/**
		 * @param {String} where
		 * @return {Array}
		 */
		public function comboScr($where) {
			$size = 0;

			$this->setRead($where, "");
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($size, "situacoes_contatos.id", $row["situacoes_contatos.id"]);
				$this->setResponse($size, "situacoes_contatos.situacao_contato", $row["situacoes_contatos.situacao_contato"]);
				$this->setResponse($size, "situacoes_contatos.selected", "selected");
					
				$size++;
			}
			
			$this->connection->free($result);
			
			$this->setResponse(0, "size", $size);

			return $this->getResponse();
		}

	}

?>