<?php
			
	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz 
	 */
	 
	namespace src\model; 
	
	class Tipos_colunasDao {
	
		private $connection;
		
		/*
		 * Constant variables
		 */
		private $create = "INSERT INTO tipos_colunas (
				tipo_coluna
				, cadastrado
				, modificado
				) VALUES";
				
		public $read = 
				"tipos_colunas.id AS \"tipos_colunas.id\"
				, tipos_colunas.tipo_coluna AS \"tipos_colunas.tipo_coluna\"
				, tipos_colunas.cadastrado AS \"tipos_colunas.cadastrado\"
				, tipos_colunas.modificado AS \"tipos_colunas.modificado\"
				";
				
		private $update = "UPDATE tipos_colunas SET";
		private $delete = "DELETE FROM tipos_colunas";
		
		public $from = "tipos_colunas tipos_colunas";
		
		/*
		 * Parameters
		 */
		private $where;
		private $order;
		
		// Dynamic query
		private $sql;
		
		// Controller response
		private $response;	
		
		/**
		 * @param {Object} connection
		 */
		public function __construct($connection) {
			$this->connection = $connection;
		}

		/**
		 * @param {Tipos_colunas}tipos_colunas
		 */
		public function setCreate($tipos_colunas) {		
			$this->sql = $this->create . " (\"" . 
					$tipos_colunas->getTipo_coluna() .
					"\", \"" . $tipos_colunas->getCadastrado() .
					"\", \"" . $tipos_colunas->getModificado() .
					"\")";
		}
		
		/**
		 * @return {String}
		 */
		public function getCreate() {
			return $this->sql;
		}	
		
		/**
		 * @param {String} where
		 * @param {String} order
		 */
		public function setRead($where, $order) {
			
			$this->setWhere($where);
			$this->setOrder($order);
			
			$this->sql = "SELECT " . $this->read . " FROM " . $this->getFrom() . 
					$this->getWhere() . "
				" . $this->getOrder();
		}
		
		/**
		 * @return {String}
		 */
		public function getRead() {
			return $this->sql;
		}
		
		/**
		 * @param {Tipos_colunas}tipos_colunas  
		 * @param {String} where
		 */
		public function setUpdate($tipos_colunas, $where) {
			$this->setWhere($where);
			
			$this->sql = $this->update . 
					" id = \"" . $tipos_colunas->getId() . 
					"\", tipo_coluna = \"" . $tipos_colunas->getTipo_coluna() . 
					"\", modificado = \"" . $tipos_colunas->getModificado() . 
					"\"" . $this->getWhere();
		}
		
		/**
		 * @return {String}
		 */
		public function getUpdate() {
			return $this->sql;
		}
		
		/**
		 * @param {String} where
		 */
		public function setDelete($where) {	
			$this->setWhere($where);
			
			$this->sql = $this->delete . $this->getWhere();
		}
		
		/**
		 * @return {String}
		 */
		public function getDelete() {
			return $this->sql;
		}
		
		/**
		 * @return {String}
		 */
		public function getFrom() {
			return $this->from;
		}
		
		/**
		 * @param {String} where
		 */
		public function setWhere($where) {
			if ($where != "")
				$this->where = " WHERE " . $where;
			else
				$this->where = "";
		}
		
		/**
		 * @return {String}
		 */
		public function getWhere() {
			return $this->where;
		}
		
		/**
		 * @param {String} order
		 */
		public function setOrder($order) {
			if ($order != "")
				$this->order = " ORDER BY " . $order;
			else
				$this->order = "";
		}
		
		/**
		 * @return {String}
		 */
		public function getOrder() {
			return $this->order;
		}
		
		/**
		 * @param {Integer} line
		 * @param column String
		 * @param value String
		 */
		private function setResponse($line, $column, $value) {
			$this->response[$line][$column] = $value;
		}

		/**
		 * @return {Array}
		 */
		private function getResponse() {
			return $this->response;
		}

		/**
		 * @param {String} where
		 */
		private function setSize($where) {
			$this->setWhere($where);
			
			$result = $this->connection->execute(
					"SELECT count(1) AS \"tipos_colunas.size\" from tipos_colunas" . $this->getWhere());

			while ($row = $result->fetch_assoc()) {		
				$this->setResponse(0, "tipos_colunas.size", $row["tipos_colunas.size"]);
				
				$pages = ceil($row["tipos_colunas.size"] / $this->connection->getItensPerPage());
				
				$this->setResponse(0, "tipos_colunas.page", $this->connection->getPosition());
				$this->setResponse(0, "tipos_colunas.pages", $pages);
				
				$pagination = "<select id='gz-select-pagination' onchange='goPage();'>";
				
				for ($i = 1; $i <= $pages; $i++) {
					if ($i == $this->connection->getPosition())
						$pagination .= "<option value='" . $i . "' selected>" . $i . "</option>";
					else
						$pagination .= "<option value='" . $i . "'>" . $i . "</option>";
				}	

				$pagination .= "</select>";
						
				$this->setResponse(0, "tipos_colunas.pagination", $pagination);
			}

			$this->connection->free($result);
		}
		
		/**
		 * @param {Integer} line
		 */
		public function setDivLine($line) {
			$this->setResponse($line - 1, "@_START_LINE_TWO", modelStartLine($line, 2));
			$this->setResponse($line - 1, "@_END_LINE_TWO", modelEndLine($line, 2));

			$this->setResponse($line - 1, "@_START_LINE_THREE", modelStartLine($line, 3));
			$this->setResponse($line - 1, "@_END_LINE_THREE", modelEndLine($line, 3));
			
			$this->setResponse($line - 1, "@_START_LINE_FOUR", modelStartLine($line, 4));
			$this->setResponse($line - 1, "@_END_LINE_FOUR", modelEndLine($line, 4));
		}
		
		/**
		 * @param {Integer} line
		 */
		public function checkDivLine($line) {
			if (modelCheckEndLine($line, 2) != "")
				$this->setResponse($line - 1, "@_END_LINE_TWO", modelCheckEndLine($line, 2));
			
			if (modelCheckEndLine($line, 3) != "")
				$this->setResponse($line - 1, "@_END_LINE_THREE", modelCheckEndLine($line, 3));		

			if (modelCheckEndLine($line, 4) != "")
				$this->setResponse($line - 1, "@_END_LINE_FOUR", modelCheckEndLine($line, 4));			
		}	

		/**
		 * @param {String} log
		 */
		private function setLog($log) {
			$this->setResponse(0, "log", $log);
		}
		
		/**
		 * @param {Tipos_colunas} tipos_colunas 
		 * @return {Boolean}
		 */
		public function create($tipos_colunas) {
			$result = "";

			$this->setCreate($tipos_colunas);
			$result = $this->connection->execute($this->getCreate());
			
			return $result;
		}

		/**
		 * @param {String} where
		 * @param {String} order
		 * @param {Boolean} wp
		 * @param {Array}
		 */
		public function read($where, $order, $wp) {
			$line = 0;

			$this->setRead($where, $order);
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($line, "tipos_colunas.id", $row["tipos_colunas.id"]);
				$this->setResponse($line, "tipos_colunas.tipo_coluna", $row["tipos_colunas.tipo_coluna"]);
				$this->setResponse($line, "tipos_colunas.tipo_coluna.format.json", modelDoubleQuotesJson($row["tipos_colunas.tipo_coluna"]));
				$this->setResponse($line, "tipos_colunas.tipo_coluna.format", modelDoubleQuotes($row["tipos_colunas.tipo_coluna"]));
				$this->setResponse($line, "tipos_colunas.tipo_coluna.view", addLine($row["tipos_colunas.tipo_coluna"]));
				$this->setResponse($line, "tipos_colunas.cadastrado", modelDateTime($row["tipos_colunas.cadastrado"]));
				$this->setResponse($line, "tipos_colunas.modificado", modelDateTime($row["tipos_colunas.modificado"]));
			
				$this->setResponse($line, "tipos_colunas.line", $line);
			
				$line++;
				
				if ($wp)
					$this->setDivLine($line);
			}

			$this->connection->free($result);
			
			if ($wp && $line > 0) {
				$this->checkDivLine($line);
				
				$this->setSize($where);
			}

			return $this->getResponse();
		}

		/**
		 * @param {Tipos_colunas} tipos_colunas 
		 * @return {Boolean}
		 */
		public function update($tipos_colunas) {
			$result = "";
			
			$this->setUpdate($tipos_colunas, "tipos_colunas.id = " . $tipos_colunas->getId());
			$result = $this->connection->execute($this->getUpdate());

			return $result;
		}

		/**
		 * @param {String} where
		 * @return {Boolean}
		 */
		public function delete($where) {
			$result = "";
			
			$this->setDelete($where);
			$result = $this->connection->execute($this->getDelete());

			return $result;
		}
		
		/**
		 * @param {Integer} selected
		 * @param {String} order
		 * @return {Array}
		 */
		public function combo($selected, $order) {
			$size = 0;

			$this->setRead("", $order);
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($size, "tipos_colunas.id", $row["tipos_colunas.id"]);
				$this->setResponse($size, "tipos_colunas.tipo_coluna", $row["tipos_colunas.tipo_coluna"]);
			
				if ($row["tipos_colunas.id"] == $selected)
					$this->setResponse($size, "tipos_colunas.selected", "selected");
				else
					$this->setResponse($size, "tipos_colunas.selected", "");
					
				$size++;
			}
			
			$this->connection->free($result);
			
			$this->setResponse(0, "size", $size);

			return $this->getResponse();
		}
		
		/**
		 * @param {String} where
		 * @return {Array}
		 */
		public function comboScr($where) {
			$size = 0;

			$this->setRead($where, "");
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($size, "tipos_colunas.id", $row["tipos_colunas.id"]);
				$this->setResponse($size, "tipos_colunas.tipo_coluna", $row["tipos_colunas.tipo_coluna"]);
				$this->setResponse($size, "tipos_colunas.selected", "selected");
					
				$size++;
			}
			
			$this->connection->free($result);
			
			$this->setResponse(0, "size", $size);

			return $this->getResponse();
		}

	}

?>