<?php
			
	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz 
	 */
	 
	namespace src\model; 
	
	class Tipos_linhasDao {
	
		private $connection;
		
		/*
		 * Constant variables
		 */
		private $create = "INSERT INTO tipos_linhas (
				tipo_linha
				, cadastrado
				, modificado
				) VALUES";
				
		public $read = 
				"tipos_linhas.id AS \"tipos_linhas.id\"
				, tipos_linhas.tipo_linha AS \"tipos_linhas.tipo_linha\"
				, tipos_linhas.cadastrado AS \"tipos_linhas.cadastrado\"
				, tipos_linhas.modificado AS \"tipos_linhas.modificado\"
				";
				
		private $update = "UPDATE tipos_linhas SET";
		private $delete = "DELETE FROM tipos_linhas";
		
		public $from = "tipos_linhas tipos_linhas";
		
		/*
		 * Parameters
		 */
		private $where;
		private $order;
		
		// Dynamic query
		private $sql;
		
		// Controller response
		private $response;	
		
		/**
		 * @param {Object} connection
		 */
		public function __construct($connection) {
			$this->connection = $connection;
		}

		/**
		 * @param {Tipos_linhas}tipos_linhas
		 */
		public function setCreate($tipos_linhas) {		
			$this->sql = $this->create . " (\"" . 
					$tipos_linhas->getTipo_linha() .
					"\", \"" . $tipos_linhas->getCadastrado() .
					"\", \"" . $tipos_linhas->getModificado() .
					"\")";
		}
		
		/**
		 * @return {String}
		 */
		public function getCreate() {
			return $this->sql;
		}	
		
		/**
		 * @param {String} where
		 * @param {String} order
		 */
		public function setRead($where, $order) {
			
			$this->setWhere($where);
			$this->setOrder($order);
			
			$this->sql = "SELECT " . $this->read . " FROM " . $this->getFrom() . 
					$this->getWhere() . "
				" . $this->getOrder();
		}
		
		/**
		 * @return {String}
		 */
		public function getRead() {
			return $this->sql;
		}
		
		/**
		 * @param {Tipos_linhas}tipos_linhas  
		 * @param {String} where
		 */
		public function setUpdate($tipos_linhas, $where) {
			$this->setWhere($where);
			
			$this->sql = $this->update . 
					" id = \"" . $tipos_linhas->getId() . 
					"\", tipo_linha = \"" . $tipos_linhas->getTipo_linha() . 
					"\", modificado = \"" . $tipos_linhas->getModificado() . 
					"\"" . $this->getWhere();
		}
		
		/**
		 * @return {String}
		 */
		public function getUpdate() {
			return $this->sql;
		}
		
		/**
		 * @param {String} where
		 */
		public function setDelete($where) {	
			$this->setWhere($where);
			
			$this->sql = $this->delete . $this->getWhere();
		}
		
		/**
		 * @return {String}
		 */
		public function getDelete() {
			return $this->sql;
		}
		
		/**
		 * @return {String}
		 */
		public function getFrom() {
			return $this->from;
		}
		
		/**
		 * @param {String} where
		 */
		public function setWhere($where) {
			if ($where != "")
				$this->where = " WHERE " . $where;
			else
				$this->where = "";
		}
		
		/**
		 * @return {String}
		 */
		public function getWhere() {
			return $this->where;
		}
		
		/**
		 * @param {String} order
		 */
		public function setOrder($order) {
			if ($order != "")
				$this->order = " ORDER BY " . $order;
			else
				$this->order = "";
		}
		
		/**
		 * @return {String}
		 */
		public function getOrder() {
			return $this->order;
		}
		
		/**
		 * @param {Integer} line
		 * @param column String
		 * @param value String
		 */
		private function setResponse($line, $column, $value) {
			$this->response[$line][$column] = $value;
		}

		/**
		 * @return {Array}
		 */
		private function getResponse() {
			return $this->response;
		}

		/**
		 * @param {String} where
		 */
		private function setSize($where) {
			$this->setWhere($where);
			
			$result = $this->connection->execute(
					"SELECT count(1) AS \"tipos_linhas.size\" from tipos_linhas" . $this->getWhere());

			while ($row = $result->fetch_assoc()) {		
				$this->setResponse(0, "tipos_linhas.size", $row["tipos_linhas.size"]);
				
				$pages = ceil($row["tipos_linhas.size"] / $this->connection->getItensPerPage());
				
				$this->setResponse(0, "tipos_linhas.page", $this->connection->getPosition());
				$this->setResponse(0, "tipos_linhas.pages", $pages);
				
				$pagination = "<select id='gz-select-pagination' onchange='goPage();'>";
				
				for ($i = 1; $i <= $pages; $i++) {
					if ($i == $this->connection->getPosition())
						$pagination .= "<option value='" . $i . "' selected>" . $i . "</option>";
					else
						$pagination .= "<option value='" . $i . "'>" . $i . "</option>";
				}	

				$pagination .= "</select>";
						
				$this->setResponse(0, "tipos_linhas.pagination", $pagination);
			}

			$this->connection->free($result);
		}
		
		/**
		 * @param {Integer} line
		 */
		public function setDivLine($line) {
			$this->setResponse($line - 1, "@_START_LINE_TWO", modelStartLine($line, 2));
			$this->setResponse($line - 1, "@_END_LINE_TWO", modelEndLine($line, 2));

			$this->setResponse($line - 1, "@_START_LINE_THREE", modelStartLine($line, 3));
			$this->setResponse($line - 1, "@_END_LINE_THREE", modelEndLine($line, 3));
			
			$this->setResponse($line - 1, "@_START_LINE_FOUR", modelStartLine($line, 4));
			$this->setResponse($line - 1, "@_END_LINE_FOUR", modelEndLine($line, 4));
		}
		
		/**
		 * @param {Integer} line
		 */
		public function checkDivLine($line) {
			if (modelCheckEndLine($line, 2) != "")
				$this->setResponse($line - 1, "@_END_LINE_TWO", modelCheckEndLine($line, 2));
			
			if (modelCheckEndLine($line, 3) != "")
				$this->setResponse($line - 1, "@_END_LINE_THREE", modelCheckEndLine($line, 3));		

			if (modelCheckEndLine($line, 4) != "")
				$this->setResponse($line - 1, "@_END_LINE_FOUR", modelCheckEndLine($line, 4));			
		}	

		/**
		 * @param {String} log
		 */
		private function setLog($log) {
			$this->setResponse(0, "log", $log);
		}
		
		/**
		 * @param {Tipos_linhas} tipos_linhas 
		 * @return {Boolean}
		 */
		public function create($tipos_linhas) {
			$result = "";

			$this->setCreate($tipos_linhas);
			$result = $this->connection->execute($this->getCreate());
			
			return $result;
		}

		/**
		 * @param {String} where
		 * @param {String} order
		 * @param {Boolean} wp
		 * @param {Array}
		 */
		public function read($where, $order, $wp) {
			$line = 0;

			$this->setRead($where, $order);
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($line, "tipos_linhas.id", $row["tipos_linhas.id"]);
				$this->setResponse($line, "tipos_linhas.tipo_linha", $row["tipos_linhas.tipo_linha"]);
				$this->setResponse($line, "tipos_linhas.tipo_linha.format.json", modelDoubleQuotesJson($row["tipos_linhas.tipo_linha"]));
				$this->setResponse($line, "tipos_linhas.tipo_linha.format", modelDoubleQuotes($row["tipos_linhas.tipo_linha"]));
				$this->setResponse($line, "tipos_linhas.tipo_linha.view", addLine($row["tipos_linhas.tipo_linha"]));
				$this->setResponse($line, "tipos_linhas.cadastrado", modelDateTime($row["tipos_linhas.cadastrado"]));
				$this->setResponse($line, "tipos_linhas.modificado", modelDateTime($row["tipos_linhas.modificado"]));
			
				$this->setResponse($line, "tipos_linhas.line", $line);
			
				$line++;
				
				if ($wp)
					$this->setDivLine($line);
			}

			$this->connection->free($result);
			
			if ($wp && $line > 0) {
				$this->checkDivLine($line);
				
				$this->setSize($where);
			}

			return $this->getResponse();
		}

		/**
		 * @param {Tipos_linhas} tipos_linhas 
		 * @return {Boolean}
		 */
		public function update($tipos_linhas) {
			$result = "";
			
			$this->setUpdate($tipos_linhas, "tipos_linhas.id = " . $tipos_linhas->getId());
			$result = $this->connection->execute($this->getUpdate());

			return $result;
		}

		/**
		 * @param {String} where
		 * @return {Boolean}
		 */
		public function delete($where) {
			$result = "";
			
			$this->setDelete($where);
			$result = $this->connection->execute($this->getDelete());

			return $result;
		}
		
		/**
		 * @param {Integer} selected
		 * @param {String} order
		 * @return {Array}
		 */
		public function combo($selected, $order) {
			$size = 0;

			$this->setRead("", $order);
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($size, "tipos_linhas.id", $row["tipos_linhas.id"]);
				$this->setResponse($size, "tipos_linhas.tipo_linha", $row["tipos_linhas.tipo_linha"]);
			
				if ($row["tipos_linhas.id"] == $selected)
					$this->setResponse($size, "tipos_linhas.selected", "selected");
				else
					$this->setResponse($size, "tipos_linhas.selected", "");
					
				$size++;
			}
			
			$this->connection->free($result);
			
			$this->setResponse(0, "size", $size);

			return $this->getResponse();
		}
		
		/**
		 * @param {String} where
		 * @return {Array}
		 */
		public function comboScr($where) {
			$size = 0;

			$this->setRead($where, "");
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($size, "tipos_linhas.id", $row["tipos_linhas.id"]);
				$this->setResponse($size, "tipos_linhas.tipo_linha", $row["tipos_linhas.tipo_linha"]);
				$this->setResponse($size, "tipos_linhas.selected", "selected");
					
				$size++;
			}
			
			$this->connection->free($result);
			
			$this->setResponse(0, "size", $size);

			return $this->getResponse();
		}

	}

?>