<?php

	/**
	 * Generated by Getz Framework
	 *
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz
	 */
	 
	use lib\getz;
	use src\logic;	 
	use src\model;	 
	
	require_once($_DOCUMENT_ROOT . "/lib/getz/Activator.php");
	
	/*
	 * Filters
	 */
	$where = "";
	
	if ($search != "")
		$where = "contatos.contato LIKE \"%" . $search . "%\"";	
		
	if ($code != "")
		$where = "contatos.id = " . $code;
	
	if (isset($_GET["friendly"]))
		$where = "contatos.contato = \"" . removeLine($_GET["friendly"]) . "\"";	
		
	$limit = "";	
	
	if ($order != "") {
		$o = explode("<gz>", $order);
		if ($method == "stateReadAll" || $method == "stateCalledAll") {
			$limit = $o[0] . " " . $o[1];
		} else {
			$limit = $o[0] . " " . $o[1] . " LIMIT " . 
					(($position * $itensPerPage) - $itensPerPage) . ", " . $itensPerPage;
		}		
	} else {
		if ($method == "stateReadAll" || $method == "stateCalledAll") {
			$limit = "contatos.ordem ASC";	
		} else {
			if ($position > 0 && $itensPerPage > 0) {
				$limit = "contatos.id DESC LIMIT " . 
						(($position * $itensPerPage) - $itensPerPage) . ", " . $itensPerPage;	
			}
		}
	}
	
	/**************************************************
	 * Webpage
	 **************************************************/		
	
	/*
	 * Page
	 */
	if ($method == "page") {
		/*
		 * SEO
		 */
		$view->setTitle(ucfirst($screen));
		$view->setDescription("");
		$view->setKeywords("");
		
		$daoFactory->beginTransaction();
		$response["contatos"] = $daoFactory->getContatosDao()->read($where, $limit, true);
		$daoFactory->close();
		
		if (isset($_GET["friendly"]))
			$view->setTitle($response["contatos"][0]["contatos.contato"]);

		echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/header.html", $response);
		
		echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . 
				(isset($_GET["friendly"]) ? "/html/contatos.html" : "/html/contatos.html"), $response);
		
		echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/footer.html", $response);
	}
	
	/**************************************************
	 * Webservice
	 **************************************************/	

	/*
	 * Create
	 */
	else if ($method == "api-create") {
		enableCORS();
		if (isset($_POST["request"])) {
			$request = json_decode($_POST["request"], true);
			// $request[0]["@_PARAM"] = $daoFactory->prepare($request[0]["@_PARAM"]); // Prepare with sql injection.

			$daoFactory->beginTransaction();
			$contatos = new model\Contatos();
			$contatos->setContato(logicNull($request["contatos.contato"]));
			$contatos->setNome(logicNull($request["contatos.nome"]));
			$contatos->setEmail(logicNull($request["contatos.email"]));
			$contatos->setCelular(logicNull($request["contatos.celular"]));
			$contatos->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$contatos->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$contatos->setSituacao_contato($request["contatos.situacao_contato"]);
			
			$resultDao = $daoFactory->getContatosDao()->create($contatos);

			if ($resultDao) {
				$daoFactory->commit();
				$response["message"] = "success";
			} else {							
				$daoFactory->rollback();
				$response["message"] = "error";
			}

			$daoFactory->close();
		} else {
			$response["message"] = "error";
		}
		
		echo $view->json($response);
	}
	
	/*
	 * Read
	 */
	else if ($method == "api-read") {
		enableCORS();
		
		if (isset($_POST["request"])) {
			$request = json_decode($_POST["request"], true);
			
			$limit = "contatos.id DESC LIMIT " . 
					(($request[0]["page"] * $request[0]["pageSize"]) - 
					$request[0]["pageSize"]) . ", " . $request[0]["pageSize"];	
		}
		
		$daoFactory->beginTransaction();
		$contatos = $daoFactory->getContatosDao()->read("", $limit, false);
		$daoFactory->close();
		
		echo $view->json($contatos);
	}
	
	/*
	 * Update
	 */
	else if ($method == "api-update") {	
		enableCORS();
		if (isset($_POST["request"])) {
			$request = json_decode($_POST["request"], true);
			// $request[0]["@_PARAM"] = $daoFactory->prepare($request[0]["@_PARAM"]); // Prepare with sql injection.
			
			$contatos = new model\Contatos();
			$contatos->setId($request["contatos.id"]);
			$contatos->setContato(logicNull($request["contatos.contato"]));
			$contatos->setNome(logicNull($request["contatos.nome"]));
			$contatos->setEmail(logicNull($request["contatos.email"]));
			$contatos->setCelular(logicNull($request["contatos.celular"]));
			$contatos->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$contatos->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$contatos->setSituacao_contato($request["contatos.situacao_contato"]);
			
			$daoFactory->beginTransaction();
			$resultDao = $daoFactory->getContatosDao()->update($contatos);

			if ($resultDao) {
				$daoFactory->commit();
				$response["message"] = "success";
			} else {							
				$daoFactory->rollback();
				$response["message"] = "error";
			}

			$daoFactory->close();
		} else {
			$response["message"] = "error";
		}
		
		echo $view->json($response);
	}
	
	/* 
	 * Delete
	 */
	else if ($method == "api-delete") {
		enableCORS();
		if (isset($_POST["request"])) {
			$request = json_decode($_POST["request"], true);
			$request["contatos.id"] = $daoFactory->prepare($request["contatos.id"]); // Prepare with sql injection.
				
			$result = true;
			$lines = explode("<gz>", $request["contatos.id"]);

			$daoFactory->beginTransaction();

			for ($i = 0; $i < sizeof($lines); $i++) {
				$where = "contatos.id = " . $lines[$i];
				
				$resultDao = $daoFactory->getContatosDao()->delete($where);
				$result = !$result ? false : (!$resultDao ? false : true);
			}

			if ($result) {
				$daoFactory->commit();
				$response["message"] = "success";
			} else {							
				$daoFactory->rollback();
				$response["message"] = "error";
			}

			$daoFactory->close();
		} else {
			$response["message"] = "error";
		} 

		echo $view->json($response);
	}
	
	else if ($method == "changeOrder") {		
		$result = true;
		$daoFactory->beginTransaction();
		$call = $daoFactory->getContatosDao()->read("contatos.id = " . $form[0], "", false);
		$answer = $daoFactory->getContatosDao()->read("contatos.id = " . $form[1], "", false);
		$contatosDao = $daoFactory->getContatosDao()->read("contatos.ordem >= " . $answer[0]["contatos.ordem"], "", false);
		if (is_array($contatosDao) && sizeof($contatosDao) > 0) {
			for ($x = 0; $x < sizeof($contatosDao); $x++) {
				$contatos = new model\Contatos();
				$contatos->setId($contatosDao[$x]["contatos.id"]);
				$contatos->setContato(logicNull($contatosDao[$x]["contatos.contato"]));
			$contatos->setNome(logicNull($contatosDao[$x]["contatos.nome"]));
			$contatos->setEmail(logicNull($contatosDao[$x]["contatos.email"]));
			$contatos->setCelular(logicNull($contatosDao[$x]["contatos.celular"]));
			$contatos->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$contatos->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$contatos->setSituacao_contato($contatosDao[$x]["contatos.situacao_contato"]);
			
				$resultDao = $daoFactory->getContatosDao()->update($contatos);			
				$result = !$result ? false : (!$resultDao ? false : true);
			}
			$contatos = new model\Contatos();
			$contatos->setId($call[0]["contatos.id"]);
			$contatos->setContato(logicNull($call[0]["contatos.contato"]));
			$contatos->setNome(logicNull($call[0]["contatos.nome"]));
			$contatos->setEmail(logicNull($call[0]["contatos.email"]));
			$contatos->setCelular(logicNull($call[0]["contatos.celular"]));
			$contatos->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$contatos->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$contatos->setSituacao_contato($call[0]["contatos.situacao_contato"]);
			
			$resultDao = $daoFactory->getContatosDao()->update($contatos);			
			$result = !$result ? false : (!$resultDao ? false : true);
		}
		if ($result) {
			$daoFactory->commit();
			$response[0]["message"] = "success";
		} else {							
			$daoFactory->rollback();
			$response[0]["message"] = "error";
		}
		$daoFactory->close();
		echo $darth->json($response);
	}
	
	/**************************************************
	 * System
	 **************************************************/	
	
	else {
		if (!getActiveSession($_ROOT . $_MODULE)) 
			echo "<script>goTo(\"/login/1\");</script>";
		else {
			/*
			 * Create
			 */
			if ($method == "stateCreate") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					$daoFactory->beginTransaction();
					$response["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
					$response["situacoes_contatos"] = $daoFactory->getSituacoes_contatosDao()->read("", "situacoes_contatos.id ASC", false);
					$daoFactory->close();

					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.html", getMenu($daoFactory, $_USER, $screen));
					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/contatos/contatosCRT.html", $response);
				}
			}

			/*
			 * Read
			 */
			else if ($method == "stateRead" || $method == "stateReadAll") {
				if ($method == "stateReadAll") {
					$method = "stateRead";
				}
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					$daoFactory->beginTransaction();
					$response["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
					$response["contatos"] = $daoFactory->getContatosDao()->read($where, $limit, true);
					if (!is_array($response["contatos"])) {
						$response["data_not_found"][0]["value"] = "<p>Não possui registro.</p>";
					}
					$daoFactory->close();

					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.html", getMenu($daoFactory, $_USER, $screen));
					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/contatos/contatosRD.html", $response);
				}
			}

			/*
			 * Update
			 */
			else if ($method == "stateUpdate") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					$daoFactory->beginTransaction();
					$response["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
					$response["contatos"] = $daoFactory->getContatosDao()->read($where, "", true);
					$response["contatos"][0]["contatos.situacoes_contatos"] = $daoFactory->getSituacoes_contatosDao()->read("", "situacoes_contatos.id ASC", false);
					for ($x = 0; $x < sizeof($response["contatos"][0]["contatos.situacoes_contatos"]); $x++) {
						if ($response["contatos"][0]["contatos.situacoes_contatos"][$x]["situacoes_contatos.id"] == 
								$response["contatos"][0]["contatos.situacao_contato"]) {
							$response["contatos"][0]["contatos.situacoes_contatos"][$x]["situacoes_contatos.selected"] = "selected";
						}
					}
					$daoFactory->close();

					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.html", getMenu($daoFactory, $_USER, $screen));
					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/contatos/contatosUPD.html", $response);
				}
			}

			/*
			 * Called
			 */
			else if ($method == "stateCalled" || $method == "stateCalledAll") {
				if ($method == "stateCalledAll") {
					$method = "stateCalled";
				}
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					/*
					 * Insert your foreign key here
					 */
					if ($where != "")
						$where .= " AND contatos.@_FOREIGN_KEY = " . $base;
					else 
						$where = "contatos.@_FOREIGN_KEY = " . $base;
						
					$daoFactory->beginTransaction();
					$response["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
					$response["contatos"] = $daoFactory->getContatosDao()->read($where, $limit, true);
					if (!is_array($response["contatos"])) {
						$response["data_not_found"][0]["value"] = "<p>Não possui registro.</p>";
					}
					$daoFactory->close();

					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.html", getMenu($daoFactory, $_USER, $screen));
					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/contatos/contatosCLL.html", $response);
				}
			}

			/*
			 * Screen
			 */
			else if ($method == "screen") {
				if ($base != "") {
					$arrBase = explode("<gz>", $base);
					
					if (sizeof($arrBase) > 1) {
						if ($where != "")
							$where .= " AND contatos.@_FOREIGN_KEY = " . $arrBase[1];
						else
							$where = "contatos.@_FOREIGN_KEY = " . $arrBase[1];
					}
				}
				
				$limit = "contatos.id DESC LIMIT " . (($position * 5) - 5) . ", 5";

				$daoFactory->beginTransaction();
				$response["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
				$response["contatos"] = $daoFactory->getContatosDao()->read($where, $limit, true);
				$daoFactory->close();

				echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/contatos/contatosSCR.html", $response) . 
						"<size>" . (is_array($response["contatos"]) ? $response["contatos"][0]["contatos.size"] : 0) . "<theme>455a64";
			}

			/*
			 * Screen handler
			 */
			else if ($method == "screenHandler") {	
				$where = "";

				// Get value from combo
				$cmb = explode("<gz>", $search);

				if ($cmb[1] != "")
					$where = "contatos.id = " . $cmb[1];

				$daoFactory->beginTransaction();
				$response["contatos"] = $daoFactory->getContatosDao()->comboScr($where);
				$daoFactory->close();

				echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/contatos/contatosCMB.html", $response);
			}

			/*
			 * Create
			 */
			else if ($method == "create") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method)) {
					$response["message"] = "permission";
					
					echo $view->json($response);
				} else {
					$contatos = new model\Contatos();
					$contatos->setContato(logicNull($form[0]));
					$contatos->setNome(logicNull($form[1]));
					$contatos->setEmail(logicNull($form[2]));
					$contatos->setCelular(logicNull($form[3]));
					$contatos->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					$contatos->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					$contatos->setSituacao_contato($form[4]);
					
					$daoFactory->beginTransaction();
					$resultDao = $daoFactory->getContatosDao()->create($contatos);

					if ($resultDao) {
						$daoFactory->commit();
						$response["message"] = "success";				
					} else {							
						$daoFactory->rollback();
						$response["message"] = "error";
					}

					$daoFactory->close();

					echo $view->json($response);
				}
			}

			/*
			 * Action update
			 */
			else if ($method == "update") {	
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method)) {
					$response["message"] = "permission";
					
					echo $view->json($response);
				} else {
					$contatos = new model\Contatos();
					$contatos->setId($code);
					$contatos->setContato(logicNull($form[0]));
					$contatos->setNome(logicNull($form[1]));
					$contatos->setEmail(logicNull($form[2]));
					$contatos->setCelular(logicNull($form[3]));
					$contatos->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					$contatos->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					$contatos->setSituacao_contato($form[4]);
					
					$daoFactory->beginTransaction();
					$resultDao = $daoFactory->getContatosDao()->update($contatos);

					if ($resultDao) {
						$daoFactory->commit();
						$response["message"] = "success";
					} else {							
						$daoFactory->rollback();
						$response["message"] = "error";
					}

					$daoFactory->close();

					echo $view->json($response);
				}
			}
			
			/* 
			 * Action delete
			 */
			else if ($method == "delete") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method)) {
					$response["message"] = "permission";
					
					echo $view->json($response);
				} else {
					$result = true;
					$lines = explode("<gz>", $code);

					$daoFactory->beginTransaction();

					for ($i = 1; $i < sizeof($lines); $i++) {
						$where = "contatos.id = " . $lines[$i];
						
						$resultDao = $daoFactory->getContatosDao()->delete($where);
						$result = !$result ? false : (!$resultDao ? false : true);
					}

					if ($result) {
						$daoFactory->commit();
						$response["message"] = "success";
					} else {							
						$daoFactory->rollback();
						$response["message"] = "error";
					}

					$daoFactory->close();

					echo $view->json($response);	
				}
			}
		}
	}

?>