<?php

	/**
	 * Generated by Getz Framework
	 *
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz
	 */
	 
	use lib\getz;
	use src\logic;	 
	use src\model;	 
	
	require_once($_DOCUMENT_ROOT . "/lib/getz/Activator.php");
	
	/*
	 * Filters
	 */
	$where = "";
	
	if ($search != "")
		$where = "elemento_conteudos.elemento_conteudo LIKE \"%" . $search . "%\"";	
		
	if ($code != "")
		$where = "elemento_conteudos.id = " . $code;
	
	if (isset($_GET["friendly"]))
		$where = "elemento_conteudos.elemento_conteudo = \"" . removeLine($_GET["friendly"]) . "\"";	
		
	$limit = "";	
	
	if ($order != "") {
		$o = explode("<gz>", $order);
		if ($method == "stateReadAll" || $method == "stateCalledAll") {
			$limit = $o[0] . " " . $o[1];
		} else {
			$limit = $o[0] . " " . $o[1] . " LIMIT " . 
					(($position * $itensPerPage) - $itensPerPage) . ", " . $itensPerPage;
		}		
	} else {
		if ($method == "stateReadAll" || $method == "stateCalledAll") {
			$limit = "elemento_conteudos.ordem ASC";	
		} else {
			if ($position > 0 && $itensPerPage > 0) {
				$limit = "elemento_conteudos.ordem ASC LIMIT " . 
						(($position * $itensPerPage) - $itensPerPage) . ", " . $itensPerPage;	
			}
		}
	}
	
	/**************************************************
	 * Webpage
	 **************************************************/		
	
	/*
	 * Page
	 */
	if ($method == "page") {
		/*
		 * SEO
		 */
		$view->setTitle(ucfirst($screen));
		$view->setDescription("");
		$view->setKeywords("");
		
		$daoFactory->beginTransaction();
		$response["elemento_conteudos"] = $daoFactory->getElemento_conteudosDao()->read($where, $limit, true);
		$daoFactory->close();
		
		if (isset($_GET["friendly"]))
			$view->setTitle($response["elemento_conteudos"][0]["elemento_conteudos.elemento_conteudo"]);

		echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/header.html", $response);
		
		echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . 
				(isset($_GET["friendly"]) ? "/html/elemento_conteudos.html" : "/html/elemento_conteudos.html"), $response);
		
		echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/footer.html", $response);
	}
	
	/**************************************************
	 * Webservice
	 **************************************************/	

	/*
	 * Create
	 */
	else if ($method == "api-create") {
		enableCORS();
		if (isset($_POST["request"])) {
			$request = json_decode($_POST["request"], true);
			// $request[0]["@_PARAM"] = $daoFactory->prepare($request[0]["@_PARAM"]); // Prepare with sql injection.

			$daoFactory->beginTransaction();
			$elemento_conteudos = new model\Elemento_conteudos();
			$elemento_conteudos->setElemento_conteudo(logicNull($request["elemento_conteudos.elemento_conteudo"]));
			
			$elemento_conteudosDao = $daoFactory->getElemento_conteudosDao()->read("", "elemento_conteudos.ordem DESC LIMIT 0, 1", false);
			$elemento_conteudos->setOrdem($elemento_conteudosDao[0]["elemento_conteudos.ordem"] + 1);
				
			$elemento_conteudos->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$elemento_conteudos->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$elemento_conteudos->setElemento($request["elemento_conteudos.elemento"]);
			$elemento_conteudos->setSituacao_registro($request["elemento_conteudos.situacao_registro"]);
			$elemento_conteudos->setTipo_alinhamento_horizontal($request["elemento_conteudos.tipo_alinhamento_horizontal"]);
			$elemento_conteudos->setTipo_alinhamento_vertical($request["elemento_conteudos.tipo_alinhamento_vertical"]);
			
			$resultDao = $daoFactory->getElemento_conteudosDao()->create($elemento_conteudos);

			if ($resultDao) {
				$daoFactory->commit();
				$response["message"] = "success";
			} else {							
				$daoFactory->rollback();
				$response["message"] = "error";
			}

			$daoFactory->close();
		} else {
			$response["message"] = "error";
		}
		
		echo $view->json($response);
	}
	
	/*
	 * Read
	 */
	else if ($method == "api-read") {
		enableCORS();
		
		if (isset($_POST["request"])) {
			$request = json_decode($_POST["request"], true);
			
			$limit = "elemento_conteudos.id DESC LIMIT " . 
					(($request[0]["page"] * $request[0]["pageSize"]) - 
					$request[0]["pageSize"]) . ", " . $request[0]["pageSize"];	
		}
		
		$daoFactory->beginTransaction();
		$elemento_conteudos = $daoFactory->getElemento_conteudosDao()->read("", $limit, false);
		$daoFactory->close();
		
		echo $view->json($elemento_conteudos);
	}
	
	/*
	 * Update
	 */
	else if ($method == "api-update") {	
		enableCORS();
		if (isset($_POST["request"])) {
			$request = json_decode($_POST["request"], true);
			// $request[0]["@_PARAM"] = $daoFactory->prepare($request[0]["@_PARAM"]); // Prepare with sql injection.
			
			$elemento_conteudos = new model\Elemento_conteudos();
			$elemento_conteudos->setId($request["elemento_conteudos.id"]);
			$elemento_conteudos->setElemento_conteudo(logicNull($request["elemento_conteudos.elemento_conteudo"]));
			
			$where = "elemento_conteudos.id = " . $request["elemento_conteudos.id"];
			
			$daoFactory->beginTransaction();
			$elemento_conteudosDao = $daoFactory->getElemento_conteudosDao()->read($where, "", false);
			$daoFactory->close();

			$elemento_conteudos->setOrdem($elemento_conteudosDao[0]["elemento_conteudos.ordem"]);
				
			$elemento_conteudos->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$elemento_conteudos->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$elemento_conteudos->setElemento($request["elemento_conteudos.elemento"]);
			$elemento_conteudos->setSituacao_registro($request["elemento_conteudos.situacao_registro"]);
			$elemento_conteudos->setTipo_alinhamento_horizontal($request["elemento_conteudos.tipo_alinhamento_horizontal"]);
			$elemento_conteudos->setTipo_alinhamento_vertical($request["elemento_conteudos.tipo_alinhamento_vertical"]);
			
			$daoFactory->beginTransaction();
			$resultDao = $daoFactory->getElemento_conteudosDao()->update($elemento_conteudos);

			if ($resultDao) {
				$daoFactory->commit();
				$response["message"] = "success";
			} else {							
				$daoFactory->rollback();
				$response["message"] = "error";
			}

			$daoFactory->close();
		} else {
			$response["message"] = "error";
		}
		
		echo $view->json($response);
	}
	
	/* 
	 * Delete
	 */
	else if ($method == "api-delete") {
		enableCORS();
		if (isset($_POST["request"])) {
			$request = json_decode($_POST["request"], true);
			$request["elemento_conteudos.id"] = $daoFactory->prepare($request["elemento_conteudos.id"]); // Prepare with sql injection.
				
			$result = true;
			$lines = explode("<gz>", $request["elemento_conteudos.id"]);

			$daoFactory->beginTransaction();

			for ($i = 0; $i < sizeof($lines); $i++) {
				$where = "elemento_conteudos.id = " . $lines[$i];
				
				$resultDao = $daoFactory->getElemento_conteudosDao()->delete($where);
				$result = !$result ? false : (!$resultDao ? false : true);
			}

			if ($result) {
				$daoFactory->commit();
				$response["message"] = "success";
			} else {							
				$daoFactory->rollback();
				$response["message"] = "error";
			}

			$daoFactory->close();
		} else {
			$response["message"] = "error";
		} 

		echo $view->json($response);
	}
	
	else if ($method == "changeOrder") {		
		$result = true;
		$daoFactory->beginTransaction();
		$call = $daoFactory->getElemento_conteudosDao()->read("elemento_conteudos.id = " . $form[0], "", false);
		$answer = $daoFactory->getElemento_conteudosDao()->read("elemento_conteudos.id = " . $form[1], "", false);
		$elemento_conteudosDao = $daoFactory->getElemento_conteudosDao()->read("elemento_conteudos.ordem >= " . $answer[0]["elemento_conteudos.ordem"], "", false);
		if (is_array($elemento_conteudosDao) && sizeof($elemento_conteudosDao) > 0) {
			for ($x = 0; $x < sizeof($elemento_conteudosDao); $x++) {
				$elemento_conteudos = new model\Elemento_conteudos();
				$elemento_conteudos->setId($elemento_conteudosDao[$x]["elemento_conteudos.id"]);
				$elemento_conteudos->setElemento_conteudo(logicNull($elemento_conteudosDao[$x]["elemento_conteudos.elemento_conteudo"]));
			
			$elemento_conteudos->setOrdem($elemento_conteudosDao[$x]["elemento_conteudos.ordem"] + 1);
				
			$elemento_conteudos->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$elemento_conteudos->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$elemento_conteudos->setElemento($elemento_conteudosDao[$x]["elemento_conteudos.elemento"]);
			$elemento_conteudos->setSituacao_registro($elemento_conteudosDao[$x]["elemento_conteudos.situacao_registro"]);
			$elemento_conteudos->setTipo_alinhamento_horizontal($elemento_conteudosDao[$x]["elemento_conteudos.tipo_alinhamento_horizontal"]);
			$elemento_conteudos->setTipo_alinhamento_vertical($elemento_conteudosDao[$x]["elemento_conteudos.tipo_alinhamento_vertical"]);
			
				$resultDao = $daoFactory->getElemento_conteudosDao()->update($elemento_conteudos);			
				$result = !$result ? false : (!$resultDao ? false : true);
			}
			$elemento_conteudos = new model\Elemento_conteudos();
			$elemento_conteudos->setId($call[0]["elemento_conteudos.id"]);
			$elemento_conteudos->setElemento_conteudo(logicNull($call[0]["elemento_conteudos.elemento_conteudo"]));
			
			$elemento_conteudos->setOrdem($answer[0]["elemento_conteudos.ordem"]);
				
			$elemento_conteudos->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$elemento_conteudos->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$elemento_conteudos->setElemento($call[0]["elemento_conteudos.elemento"]);
			$elemento_conteudos->setSituacao_registro($call[0]["elemento_conteudos.situacao_registro"]);
			$elemento_conteudos->setTipo_alinhamento_horizontal($call[0]["elemento_conteudos.tipo_alinhamento_horizontal"]);
			$elemento_conteudos->setTipo_alinhamento_vertical($call[0]["elemento_conteudos.tipo_alinhamento_vertical"]);
			
			$resultDao = $daoFactory->getElemento_conteudosDao()->update($elemento_conteudos);			
			$result = !$result ? false : (!$resultDao ? false : true);
		}
		if ($result) {
			$daoFactory->commit();
			$response[0]["message"] = "success";
		} else {							
			$daoFactory->rollback();
			$response[0]["message"] = "error";
		}
		$daoFactory->close();
		echo $darth->json($response);
	}
	
	/**************************************************
	 * System
	 **************************************************/	
	
	else {
		if (!getActiveSession($_ROOT . $_MODULE)) 
			echo "<script>goTo(\"/login/1\");</script>";
		else {
			/*
			 * Create
			 */
			if ($method == "stateCreate") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					$daoFactory->beginTransaction();
					$response["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
					$response["elementos"] = $daoFactory->getElementosDao()->read("", "elementos.id ASC", false);
					$response["situacoes_registros"] = $daoFactory->getSituacoes_registrosDao()->read("", "situacoes_registros.id ASC", false);
					$response["tipos_alinhamentos_horizontais"] = $daoFactory->getTipos_alinhamentos_horizontaisDao()->read("", "tipos_alinhamentos_horizontais.id ASC", false);
					$response["tipos_alinhamentos_verticais"] = $daoFactory->getTipos_alinhamentos_verticaisDao()->read("", "tipos_alinhamentos_verticais.id ASC", false);
					$daoFactory->close();

					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.html", getMenu($daoFactory, $_USER, $screen));
					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/elemento_conteudos/elemento_conteudosCRT.html", $response);
				}
			}

			/*
			 * Read
			 */
			else if ($method == "stateRead" || $method == "stateReadAll") {
				if ($method == "stateReadAll") {
					$method = "stateRead";
				}
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					$daoFactory->beginTransaction();
					$response["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
					$response["elemento_conteudos"] = $daoFactory->getElemento_conteudosDao()->read($where, $limit, true);
					if (!is_array($response["elemento_conteudos"])) {
						$response["data_not_found"][0]["value"] = "<p>Não possui registro.</p>";
					}
					$daoFactory->close();

					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.html", getMenu($daoFactory, $_USER, $screen));
					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/elemento_conteudos/elemento_conteudosRD.html", $response);
				}
			}

			/*
			 * Update
			 */
			else if ($method == "stateUpdate") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					$daoFactory->beginTransaction();
					$response["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
					$response["elemento_conteudos"] = $daoFactory->getElemento_conteudosDao()->read($where, "", true);
					$response["elemento_conteudos"][0]["elemento_conteudos.elementos"] = $daoFactory->getElementosDao()->read("", "elementos.id ASC", false);
					for ($x = 0; $x < sizeof($response["elemento_conteudos"][0]["elemento_conteudos.elementos"]); $x++) {
						if ($response["elemento_conteudos"][0]["elemento_conteudos.elementos"][$x]["elementos.id"] == 
								$response["elemento_conteudos"][0]["elemento_conteudos.elemento"]) {
							$response["elemento_conteudos"][0]["elemento_conteudos.elementos"][$x]["elementos.selected"] = "selected";
						}
					}
					$response["elemento_conteudos"][0]["elemento_conteudos.situacoes_registros"] = $daoFactory->getSituacoes_registrosDao()->read("", "situacoes_registros.id ASC", false);
					for ($x = 0; $x < sizeof($response["elemento_conteudos"][0]["elemento_conteudos.situacoes_registros"]); $x++) {
						if ($response["elemento_conteudos"][0]["elemento_conteudos.situacoes_registros"][$x]["situacoes_registros.id"] == 
								$response["elemento_conteudos"][0]["elemento_conteudos.situacao_registro"]) {
							$response["elemento_conteudos"][0]["elemento_conteudos.situacoes_registros"][$x]["situacoes_registros.selected"] = "selected";
						}
					}
					$response["elemento_conteudos"][0]["elemento_conteudos.tipos_alinhamentos_horizontais"] = $daoFactory->getTipos_alinhamentos_horizontaisDao()->read("", "tipos_alinhamentos_horizontais.id ASC", false);
					for ($x = 0; $x < sizeof($response["elemento_conteudos"][0]["elemento_conteudos.tipos_alinhamentos_horizontais"]); $x++) {
						if ($response["elemento_conteudos"][0]["elemento_conteudos.tipos_alinhamentos_horizontais"][$x]["tipos_alinhamentos_horizontais.id"] == 
								$response["elemento_conteudos"][0]["elemento_conteudos.tipo_alinhamento_horizontal"]) {
							$response["elemento_conteudos"][0]["elemento_conteudos.tipos_alinhamentos_horizontais"][$x]["tipos_alinhamentos_horizontais.selected"] = "selected";
						}
					}
					$response["elemento_conteudos"][0]["elemento_conteudos.tipos_alinhamentos_verticais"] = $daoFactory->getTipos_alinhamentos_verticaisDao()->read("", "tipos_alinhamentos_verticais.id ASC", false);
					for ($x = 0; $x < sizeof($response["elemento_conteudos"][0]["elemento_conteudos.tipos_alinhamentos_verticais"]); $x++) {
						if ($response["elemento_conteudos"][0]["elemento_conteudos.tipos_alinhamentos_verticais"][$x]["tipos_alinhamentos_verticais.id"] == 
								$response["elemento_conteudos"][0]["elemento_conteudos.tipo_alinhamento_vertical"]) {
							$response["elemento_conteudos"][0]["elemento_conteudos.tipos_alinhamentos_verticais"][$x]["tipos_alinhamentos_verticais.selected"] = "selected";
						}
					}
					$daoFactory->close();

					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.html", getMenu($daoFactory, $_USER, $screen));
					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/elemento_conteudos/elemento_conteudosUPD.html", $response);
				}
			}

			/*
			 * Called
			 */
			else if ($method == "stateCalled" || $method == "stateCalledAll") {
				if ($method == "stateCalledAll") {
					$method = "stateCalled";
				}
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					/*
					 * Insert your foreign key here
					 */
					if ($where != "")
						$where .= " AND elemento_conteudos.@_FOREIGN_KEY = " . $base;
					else 
						$where = "elemento_conteudos.@_FOREIGN_KEY = " . $base;
						
					$daoFactory->beginTransaction();
					$response["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
					$response["elemento_conteudos"] = $daoFactory->getElemento_conteudosDao()->read($where, $limit, true);
					if (!is_array($response["elemento_conteudos"])) {
						$response["data_not_found"][0]["value"] = "<p>Não possui registro.</p>";
					}
					$daoFactory->close();

					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.html", getMenu($daoFactory, $_USER, $screen));
					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/elemento_conteudos/elemento_conteudosCLL.html", $response);
				}
			}

			/*
			 * Screen
			 */
			else if ($method == "screen") {
				if ($base != "") {
					$arrBase = explode("<gz>", $base);
					
					if (sizeof($arrBase) > 1) {
						if ($where != "")
							$where .= " AND elemento_conteudos.@_FOREIGN_KEY = " . $arrBase[1];
						else
							$where = "elemento_conteudos.@_FOREIGN_KEY = " . $arrBase[1];
					}
				}
				
				$limit = "elemento_conteudos.id DESC LIMIT " . (($position * 5) - 5) . ", 5";

				$daoFactory->beginTransaction();
				$response["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
				$response["elemento_conteudos"] = $daoFactory->getElemento_conteudosDao()->read($where, $limit, true);
				$daoFactory->close();

				echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/elemento_conteudos/elemento_conteudosSCR.html", $response) . 
						"<size>" . (is_array($response["elemento_conteudos"]) ? $response["elemento_conteudos"][0]["elemento_conteudos.size"] : 0) . "<theme>455a64";
			}

			/*
			 * Screen handler
			 */
			else if ($method == "screenHandler") {	
				$where = "";

				// Get value from combo
				$cmb = explode("<gz>", $search);

				if ($cmb[1] != "")
					$where = "elemento_conteudos.id = " . $cmb[1];

				$daoFactory->beginTransaction();
				$response["elemento_conteudos"] = $daoFactory->getElemento_conteudosDao()->comboScr($where);
				$daoFactory->close();

				echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/elemento_conteudos/elemento_conteudosCMB.html", $response);
			}

			/*
			 * Create
			 */
			else if ($method == "create") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method)) {
					$response["message"] = "permission";
					
					echo $view->json($response);
				} else {
					$elemento_conteudos = new model\Elemento_conteudos();
					$elemento_conteudos->setElemento_conteudo(logicNull($form[0]));
					
					$daoFactory->beginTransaction();
					$elemento_conteudosDao = $daoFactory->getElemento_conteudosDao()->read("", "elemento_conteudos.ordem DESC LIMIT 0, 1", false);
					$daoFactory->close();
						
					$elemento_conteudos->setOrdem($elemento_conteudosDao[0]["elemento_conteudos.ordem"] + 1);
						
					$elemento_conteudos->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					$elemento_conteudos->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					$elemento_conteudos->setElemento($form[1]);
					$elemento_conteudos->setSituacao_registro($form[2]);
					$elemento_conteudos->setTipo_alinhamento_horizontal($form[3]);
					$elemento_conteudos->setTipo_alinhamento_vertical($form[4]);
					
					$daoFactory->beginTransaction();
					$resultDao = $daoFactory->getElemento_conteudosDao()->create($elemento_conteudos);

					if ($resultDao) {
						$daoFactory->commit();
						$response["message"] = "success";				
					} else {							
						$daoFactory->rollback();
						$response["message"] = "error";
					}

					$daoFactory->close();

					echo $view->json($response);
				}
			}

			/*
			 * Action update
			 */
			else if ($method == "update") {	
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method)) {
					$response["message"] = "permission";
					
					echo $view->json($response);
				} else {
					$elemento_conteudos = new model\Elemento_conteudos();
					$elemento_conteudos->setId($code);
					$elemento_conteudos->setElemento_conteudo(logicNull($form[0]));
					
					$where = "elemento_conteudos.id = " . $code;
					
					$daoFactory->beginTransaction();
					$elemento_conteudosDao = $daoFactory->getElemento_conteudosDao()->read($where, "", false);
					$daoFactory->close();
						
					$elemento_conteudos->setOrdem($elemento_conteudosDao[0]["elemento_conteudos.ordem"]);
						
					$elemento_conteudos->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					$elemento_conteudos->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					$elemento_conteudos->setElemento($form[1]);
					$elemento_conteudos->setSituacao_registro($form[2]);
					$elemento_conteudos->setTipo_alinhamento_horizontal($form[3]);
					$elemento_conteudos->setTipo_alinhamento_vertical($form[4]);
					
					$daoFactory->beginTransaction();
					$resultDao = $daoFactory->getElemento_conteudosDao()->update($elemento_conteudos);

					if ($resultDao) {
						$daoFactory->commit();
						$response["message"] = "success";
					} else {							
						$daoFactory->rollback();
						$response["message"] = "error";
					}

					$daoFactory->close();

					echo $view->json($response);
				}
			}
			
			/* 
			 * Action delete
			 */
			else if ($method == "delete") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method)) {
					$response["message"] = "permission";
					
					echo $view->json($response);
				} else {
					$result = true;
					$lines = explode("<gz>", $code);

					$daoFactory->beginTransaction();

					for ($i = 1; $i < sizeof($lines); $i++) {
						$where = "elemento_conteudos.id = " . $lines[$i];
						
						$resultDao = $daoFactory->getElemento_conteudosDao()->delete($where);
						$result = !$result ? false : (!$resultDao ? false : true);
					}

					if ($result) {
						$daoFactory->commit();
						$response["message"] = "success";
					} else {							
						$daoFactory->rollback();
						$response["message"] = "error";
					}

					$daoFactory->close();

					echo $view->json($response);	
				}
			}
		}
	}

?>