<?php

	/**
	 * Generated by Getz Framework
	 *
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz
	 */
	 
	use lib\getz;
	use src\logic;	 
	use src\model;	 
	
	require_once($_DOCUMENT_ROOT . "/lib/getz/Activator.php");
	
	/*
	 * Filters
	 */
	$where = "";
	
	if ($search != "")
		$where = "elementos.elemento LIKE \"%" . $search . "%\"";	
		
	if ($code != "")
		$where = "elementos.id = " . $code;
	
	if (isset($_GET["friendly"]))
		$where = "elementos.elemento = \"" . removeLine($_GET["friendly"]) . "\"";	
		
	$limit = "";	
	
	if ($order != "") {
		$o = explode("<gz>", $order);
		if ($method == "stateReadAll" || $method == "stateCalledAll") {
			$limit = $o[0] . " " . $o[1];
		} else {
			$limit = $o[0] . " " . $o[1] . " LIMIT " . 
					(($position * $itensPerPage) - $itensPerPage) . ", " . $itensPerPage;
		}		
	} else {
		if ($method == "stateReadAll" || $method == "stateCalledAll") {
			$limit = "elementos.ordem ASC";	
		} else {
			if ($position > 0 && $itensPerPage > 0) {
				$limit = "elementos.ordem ASC LIMIT " . 
						(($position * $itensPerPage) - $itensPerPage) . ", " . $itensPerPage;	
			}
		}
	}
	
	/**************************************************
	 * Webpage
	 **************************************************/		
	
	/*
	 * Page
	 */
	if ($method == "page") {
		/*
		 * SEO
		 */
		$view->setTitle(ucfirst($screen));
		$view->setDescription("");
		$view->setKeywords("");
		
		$daoFactory->beginTransaction();
		$response["elementos"] = $daoFactory->getElementosDao()->read($where, $limit, true);
		$daoFactory->close();
		
		if (isset($_GET["friendly"]))
			$view->setTitle($response["elementos"][0]["elementos.elemento"]);

		echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/header.html", $response);
		
		echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . 
				(isset($_GET["friendly"]) ? "/html/elementos.html" : "/html/elementos.html"), $response);
		
		echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/footer.html", $response);
	}
	
	/**************************************************
	 * Webservice
	 **************************************************/	

	/*
	 * Create
	 */
	else if ($method == "api-create") {
		enableCORS();
		if (isset($_POST["request"])) {
			$request = json_decode($_POST["request"], true);
			// $request[0]["@_PARAM"] = $daoFactory->prepare($request[0]["@_PARAM"]); // Prepare with sql injection.

			$daoFactory->beginTransaction();
			$elementos = new model\Elementos();
			$elementos->setElemento(logicNull($request["elementos.elemento"]));
			
			$elementosDao = $daoFactory->getElementosDao()->read("", "elementos.ordem DESC LIMIT 0, 1", false);
			$elementos->setOrdem($elementosDao[0]["elementos.ordem"] + 1);
				
			$elementos->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$elementos->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$elementos->setTipo_linha($request["elementos.tipo_linha"]);
			$elementos->setTipo_coluna($request["elementos.tipo_coluna"]);
			$elementos->setSituacao_registro($request["elementos.situacao_registro"]);
			$elementos->setCor($request["elementos.cor"]);
			
			$resultDao = $daoFactory->getElementosDao()->create($elementos);

			if ($resultDao) {
				$daoFactory->commit();
				$response["message"] = "success";
			} else {							
				$daoFactory->rollback();
				$response["message"] = "error";
			}

			$daoFactory->close();
		} else {
			$response["message"] = "error";
		}
		
		echo $view->json($response);
	}
	
	/*
	 * Read
	 */
	else if ($method == "api-read") {
		enableCORS();
		
		if (isset($_POST["request"])) {
			$request = json_decode($_POST["request"], true);
			
			$limit = "elementos.id DESC LIMIT " . 
					(($request[0]["page"] * $request[0]["pageSize"]) - 
					$request[0]["pageSize"]) . ", " . $request[0]["pageSize"];	
		}
		
		$daoFactory->beginTransaction();
		$elementos = $daoFactory->getElementosDao()->read("", $limit, false);
		$daoFactory->close();
		
		echo $view->json($elementos);
	}
	
	/*
	 * Update
	 */
	else if ($method == "api-update") {	
		enableCORS();
		if (isset($_POST["request"])) {
			$request = json_decode($_POST["request"], true);
			// $request[0]["@_PARAM"] = $daoFactory->prepare($request[0]["@_PARAM"]); // Prepare with sql injection.
			
			$elementos = new model\Elementos();
			$elementos->setId($request["elementos.id"]);
			$elementos->setElemento(logicNull($request["elementos.elemento"]));
			
			$where = "elementos.id = " . $request["elementos.id"];
			
			$daoFactory->beginTransaction();
			$elementosDao = $daoFactory->getElementosDao()->read($where, "", false);
			$daoFactory->close();

			$elementos->setOrdem($elementosDao[0]["elementos.ordem"]);
				
			$elementos->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$elementos->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$elementos->setTipo_linha($request["elementos.tipo_linha"]);
			$elementos->setTipo_coluna($request["elementos.tipo_coluna"]);
			$elementos->setSituacao_registro($request["elementos.situacao_registro"]);
			$elementos->setCor($request["elementos.cor"]);
			
			$daoFactory->beginTransaction();
			$resultDao = $daoFactory->getElementosDao()->update($elementos);

			if ($resultDao) {
				$daoFactory->commit();
				$response["message"] = "success";
			} else {							
				$daoFactory->rollback();
				$response["message"] = "error";
			}

			$daoFactory->close();
		} else {
			$response["message"] = "error";
		}
		
		echo $view->json($response);
	}
	
	/* 
	 * Delete
	 */
	else if ($method == "api-delete") {
		enableCORS();
		if (isset($_POST["request"])) {
			$request = json_decode($_POST["request"], true);
			$request["elementos.id"] = $daoFactory->prepare($request["elementos.id"]); // Prepare with sql injection.
				
			$result = true;
			$lines = explode("<gz>", $request["elementos.id"]);

			$daoFactory->beginTransaction();

			for ($i = 0; $i < sizeof($lines); $i++) {
				$where = "elementos.id = " . $lines[$i];
				
				$resultDao = $daoFactory->getElementosDao()->delete($where);
				$result = !$result ? false : (!$resultDao ? false : true);
			}

			if ($result) {
				$daoFactory->commit();
				$response["message"] = "success";
			} else {							
				$daoFactory->rollback();
				$response["message"] = "error";
			}

			$daoFactory->close();
		} else {
			$response["message"] = "error";
		} 

		echo $view->json($response);
	}
	
	else if ($method == "changeOrder") {		
		$result = true;
		$daoFactory->beginTransaction();
		$call = $daoFactory->getElementosDao()->read("elementos.id = " . $form[0], "", false);
		$answer = $daoFactory->getElementosDao()->read("elementos.id = " . $form[1], "", false);
		$elementosDao = $daoFactory->getElementosDao()->read("elementos.ordem >= " . $answer[0]["elementos.ordem"], "", false);
		if (is_array($elementosDao) && sizeof($elementosDao) > 0) {
			for ($x = 0; $x < sizeof($elementosDao); $x++) {
				$elementos = new model\Elementos();
				$elementos->setId($elementosDao[$x]["elementos.id"]);
				$elementos->setElemento(logicNull($elementosDao[$x]["elementos.elemento"]));
			
			$elementos->setOrdem($elementosDao[$x]["elementos.ordem"] + 1);
				
			$elementos->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$elementos->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$elementos->setTipo_linha($elementosDao[$x]["elementos.tipo_linha"]);
			$elementos->setTipo_coluna($elementosDao[$x]["elementos.tipo_coluna"]);
			$elementos->setSituacao_registro($elementosDao[$x]["elementos.situacao_registro"]);
			$elementos->setCor($elementosDao[$x]["elementos.cor"]);
			
				$resultDao = $daoFactory->getElementosDao()->update($elementos);			
				$result = !$result ? false : (!$resultDao ? false : true);
			}
			$elementos = new model\Elementos();
			$elementos->setId($call[0]["elementos.id"]);
			$elementos->setElemento(logicNull($call[0]["elementos.elemento"]));
			
			$elementos->setOrdem($answer[0]["elementos.ordem"]);
				
			$elementos->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$elementos->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$elementos->setTipo_linha($call[0]["elementos.tipo_linha"]);
			$elementos->setTipo_coluna($call[0]["elementos.tipo_coluna"]);
			$elementos->setSituacao_registro($call[0]["elementos.situacao_registro"]);
			$elementos->setCor($call[0]["elementos.cor"]);
			
			$resultDao = $daoFactory->getElementosDao()->update($elementos);			
			$result = !$result ? false : (!$resultDao ? false : true);
		}
		if ($result) {
			$daoFactory->commit();
			$response[0]["message"] = "success";
		} else {							
			$daoFactory->rollback();
			$response[0]["message"] = "error";
		}
		$daoFactory->close();
		echo $darth->json($response);
	}
	
	/**************************************************
	 * System
	 **************************************************/	
	
	else {
		if (!getActiveSession($_ROOT . $_MODULE)) 
			echo "<script>goTo(\"/login/1\");</script>";
		else {
			/*
			 * Create
			 */
			if ($method == "stateCreate") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					$daoFactory->beginTransaction();
					$response["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
					$response["tipos_linhas"] = $daoFactory->getTipos_linhasDao()->read("", "tipos_linhas.id ASC", false);
					$response["tipos_colunas"] = $daoFactory->getTipos_colunasDao()->read("", "tipos_colunas.id ASC", false);
					$response["situacoes_registros"] = $daoFactory->getSituacoes_registrosDao()->read("", "situacoes_registros.id ASC", false);
					$response["cores"] = $daoFactory->getCoresDao()->read("cores.tipo_cor = 1", "cores.id ASC", false);
					$daoFactory->close();

					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.html", getMenu($daoFactory, $_USER, $screen));
					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/elementos/elementosCRT.html", $response);
				}
			}

			/*
			 * Read
			 */
			else if ($method == "stateRead" || $method == "stateReadAll") {
				if ($method == "stateReadAll") {
					$method = "stateRead";
				}
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					$daoFactory->beginTransaction();
					$response["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
					$response["elementos"] = $daoFactory->getElementosDao()->read($where, $limit, true);
					if (!is_array($response["elementos"])) {
						$response["data_not_found"][0]["value"] = "<p>Não possui registro.</p>";
					}
					$daoFactory->close();

					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.html", getMenu($daoFactory, $_USER, $screen));
					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/elementos/elementosRD.html", $response);
				}
			}

			/*
			 * Update
			 */
			else if ($method == "stateUpdate") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					$daoFactory->beginTransaction();
					$response["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
					$response["elementos"] = $daoFactory->getElementosDao()->read($where, "", true);
					$response["elementos"][0]["elementos.tipos_linhas"] = $daoFactory->getTipos_linhasDao()->read("", "tipos_linhas.id ASC", false);
					for ($x = 0; $x < sizeof($response["elementos"][0]["elementos.tipos_linhas"]); $x++) {
						if ($response["elementos"][0]["elementos.tipos_linhas"][$x]["tipos_linhas.id"] == 
								$response["elementos"][0]["elementos.tipo_linha"]) {
							$response["elementos"][0]["elementos.tipos_linhas"][$x]["tipos_linhas.selected"] = "selected";
						}
					}
					$response["elementos"][0]["elementos.tipos_colunas"] = $daoFactory->getTipos_colunasDao()->read("", "tipos_colunas.id ASC", false);
					for ($x = 0; $x < sizeof($response["elementos"][0]["elementos.tipos_colunas"]); $x++) {
						if ($response["elementos"][0]["elementos.tipos_colunas"][$x]["tipos_colunas.id"] == 
								$response["elementos"][0]["elementos.tipo_coluna"]) {
							$response["elementos"][0]["elementos.tipos_colunas"][$x]["tipos_colunas.selected"] = "selected";
						}
					}
					$response["elementos"][0]["elementos.situacoes_registros"] = $daoFactory->getSituacoes_registrosDao()->read("", "situacoes_registros.id ASC", false);
					for ($x = 0; $x < sizeof($response["elementos"][0]["elementos.situacoes_registros"]); $x++) {
						if ($response["elementos"][0]["elementos.situacoes_registros"][$x]["situacoes_registros.id"] == 
								$response["elementos"][0]["elementos.situacao_registro"]) {
							$response["elementos"][0]["elementos.situacoes_registros"][$x]["situacoes_registros.selected"] = "selected";
						}
					}
					$response["elementos"][0]["elementos.cores"] = $daoFactory->getCoresDao()->read("cores.tipo_cor = 1", "cores.id ASC", false);
					for ($x = 0; $x < sizeof($response["elementos"][0]["elementos.cores"]); $x++) {
						if ($response["elementos"][0]["elementos.cores"][$x]["cores.id"] == 
								$response["elementos"][0]["elementos.cor"]) {
							$response["elementos"][0]["elementos.cores"][$x]["cores.selected"] = "selected";
						}
					}
					$daoFactory->close();

					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.html", getMenu($daoFactory, $_USER, $screen));
					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/elementos/elementosUPD.html", $response);
				}
			}

			/*
			 * Called
			 */
			else if ($method == "stateCalled" || $method == "stateCalledAll") {
				if ($method == "stateCalledAll") {
					$method = "stateCalled";
				}
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					/*
					 * Insert your foreign key here
					 */
					if ($where != "")
						$where .= " AND elementos.@_FOREIGN_KEY = " . $base;
					else 
						$where = "elementos.@_FOREIGN_KEY = " . $base;
						
					$daoFactory->beginTransaction();
					$response["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
					$response["elementos"] = $daoFactory->getElementosDao()->read($where, $limit, true);
					if (!is_array($response["elementos"])) {
						$response["data_not_found"][0]["value"] = "<p>Não possui registro.</p>";
					}
					$daoFactory->close();

					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.html", getMenu($daoFactory, $_USER, $screen));
					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/elementos/elementosCLL.html", $response);
				}
			}

			/*
			 * Screen
			 */
			else if ($method == "screen") {
				if ($base != "") {
					$arrBase = explode("<gz>", $base);
					
					if (sizeof($arrBase) > 1) {
						if ($where != "")
							$where .= " AND elementos.@_FOREIGN_KEY = " . $arrBase[1];
						else
							$where = "elementos.@_FOREIGN_KEY = " . $arrBase[1];
					}
				}
				
				$limit = "elementos.id DESC LIMIT " . (($position * 5) - 5) . ", 5";

				$daoFactory->beginTransaction();
				$response["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
				$response["elementos"] = $daoFactory->getElementosDao()->read($where, $limit, true);
				$daoFactory->close();

				echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/elementos/elementosSCR.html", $response) . 
						"<size>" . (is_array($response["elementos"]) ? $response["elementos"][0]["elementos.size"] : 0) . "<theme>455a64";
			}

			/*
			 * Screen handler
			 */
			else if ($method == "screenHandler") {	
				$where = "";

				// Get value from combo
				$cmb = explode("<gz>", $search);

				if ($cmb[1] != "")
					$where = "elementos.id = " . $cmb[1];

				$daoFactory->beginTransaction();
				$response["elementos"] = $daoFactory->getElementosDao()->comboScr($where);
				$daoFactory->close();

				echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/elementos/elementosCMB.html", $response);
			}

			/*
			 * Create
			 */
			else if ($method == "create") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method)) {
					$response["message"] = "permission";
					
					echo $view->json($response);
				} else {
					$elementos = new model\Elementos();
					$elementos->setElemento(logicNull($form[0]));
					
					$daoFactory->beginTransaction();
					$elementosDao = $daoFactory->getElementosDao()->read("", "elementos.ordem DESC LIMIT 0, 1", false);
					$daoFactory->close();
						
					$elementos->setOrdem($elementosDao[0]["elementos.ordem"] + 1);
						
					$elementos->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					$elementos->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					$elementos->setTipo_linha($form[1]);
					$elementos->setTipo_coluna($form[2]);
					$elementos->setSituacao_registro($form[3]);
					$elementos->setCor($form[4]);
					
					$daoFactory->beginTransaction();
					$resultDao = $daoFactory->getElementosDao()->create($elementos);

					if ($resultDao) {
						$daoFactory->commit();
						$response["message"] = "success";				
					} else {							
						$daoFactory->rollback();
						$response["message"] = "error";
					}

					$daoFactory->close();

					echo $view->json($response);
				}
			}

			/*
			 * Action update
			 */
			else if ($method == "update") {	
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method)) {
					$response["message"] = "permission";
					
					echo $view->json($response);
				} else {
					$elementos = new model\Elementos();
					$elementos->setId($code);
					$elementos->setElemento(logicNull($form[0]));
					
					$where = "elementos.id = " . $code;
					
					$daoFactory->beginTransaction();
					$elementosDao = $daoFactory->getElementosDao()->read($where, "", false);
					$daoFactory->close();
						
					$elementos->setOrdem($elementosDao[0]["elementos.ordem"]);
						
					$elementos->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					$elementos->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					$elementos->setTipo_linha($form[1]);
					$elementos->setTipo_coluna($form[2]);
					$elementos->setSituacao_registro($form[3]);
					$elementos->setCor($form[4]);
					
					$daoFactory->beginTransaction();
					$resultDao = $daoFactory->getElementosDao()->update($elementos);

					if ($resultDao) {
						$daoFactory->commit();
						$response["message"] = "success";
					} else {							
						$daoFactory->rollback();
						$response["message"] = "error";
					}

					$daoFactory->close();

					echo $view->json($response);
				}
			}
			
			/* 
			 * Action delete
			 */
			else if ($method == "delete") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method)) {
					$response["message"] = "permission";
					
					echo $view->json($response);
				} else {
					$result = true;
					$lines = explode("<gz>", $code);

					$daoFactory->beginTransaction();

					for ($i = 1; $i < sizeof($lines); $i++) {
						$where = "elementos.id = " . $lines[$i];
						
						$resultDao = $daoFactory->getElementosDao()->delete($where);
						$result = !$result ? false : (!$resultDao ? false : true);
					}

					if ($result) {
						$daoFactory->commit();
						$response["message"] = "success";
					} else {							
						$daoFactory->rollback();
						$response["message"] = "error";
					}

					$daoFactory->close();

					echo $view->json($response);	
				}
			}
		}
	}

?>