<?php

	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz
	 */

	use lib\getz;
	use src\logic;
	use src\model;	 
	 
	require_once($_DOCUMENT_ROOT . "/lib/getz/Activator.php");

	if ($method == "page") {
		$authorization = new logic\Authorization();
		if ($authorization->isValid()) {
			header("Location: " . $view->getRoot() . "/inicio");
		} else {
			$daoFactory->beginTransaction();

			$response["curso"] = $daoFactory->getCursoDao()->read("", "curso.id ASC", true);
			// $response["noticia"] = $daoFactory->getNoticiasDao()->read("", "noticias.id ASC", true);

			$daoFactory->close();

			$response["print"] = "true";
			echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/header.html");
			echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/home.html", $response);
			echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/footer.html");
		}
	}

?>