<?php

	/**
	 * Generated by Getz Framework
	 *
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz
	 */
	 
	use lib\getz;
	use src\logic;	 
	use src\model;	 
	
	require_once($_DOCUMENT_ROOT . "/lib/getz/Activator.php");
	
	/*
	 * Filters
	 */
	$where = "";
	
	if ($search != "")
		$where = "noticias.noticia LIKE \"%" . $search . "%\"";	
		
	if ($code != "")
		$where = "noticias.id = " . $code;
	
	if (isset($_GET["friendly"]))
		$where = "noticias.noticia = \"" . removeLine($_GET["friendly"]) . "\"";	
		
	$limit = "";	
	
	if ($order != "") {
		$o = explode("<gz>", $order);
		if ($method == "stateReadAll" || $method == "stateCalledAll") {
			$limit = $o[0] . " " . $o[1];
		} else {
			$limit = $o[0] . " " . $o[1] . " LIMIT " . 
					(($position * $itensPerPage) - $itensPerPage) . ", " . $itensPerPage;
		}		
	} else {
		if ($method == "stateReadAll" || $method == "stateCalledAll") {
			$limit = "noticias.ordem ASC";	
		} else {
			if ($position > 0 && $itensPerPage > 0) {
				$limit = "noticias.id DESC LIMIT " . 
						(($position * $itensPerPage) - $itensPerPage) . ", " . $itensPerPage;	
			}
		}
	}
	
	/**************************************************
	 * Webpage
	 **************************************************/		
	
	/*
	 * Page
	 */
	if ($method == "page") {
		/*
		 * SEO
		 */
		$view->setTitle(ucfirst($screen));
		$view->setDescription("");
		$view->setKeywords("");
		
		$daoFactory->beginTransaction();
		$response["noticias"] = $daoFactory->getNoticiasDao()->read($where, $limit, true);
		$daoFactory->close();
		
		if (isset($_GET["friendly"]))
			$view->setTitle($response["noticias"][0]["noticias.noticia"]);

		echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/header.html", $response);
		
		echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . 
				(isset($_GET["friendly"]) ? "/html/noticias.html" : "/html/noticias.html"), $response);
		
		echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/footer.html", $response);
	}
	
	/**************************************************
	 * Webservice
	 **************************************************/	

	/*
	 * Create
	 */
	else if ($method == "api-create") {
		enableCORS();
		if (isset($_POST["request"])) {
			$request = json_decode($_POST["request"], true);
			// $request[0]["@_PARAM"] = $daoFactory->prepare($request[0]["@_PARAM"]); // Prepare with sql injection.

			$daoFactory->beginTransaction();
			$noticias = new model\Noticias();
			$noticias->setNoticia(logicNull($request["noticias.noticia"]));
			
			if (isset($_FILES["upload"])) {
				$upload = new getz\Upload($_FILES["upload"], 1200);
				$noticias->setFoto($upload->getName());
			} else 
				$noticias->setFoto("");
				
			$noticias->setLegenda_foto(logicNull($request["noticias.legenda_foto"]));
			$noticias->setResumo(logicNull($request["noticias.resumo"]));
			$noticias->setConteudo(logicNull($request["noticias.conteudo"]));
			$noticias->setPalavras_chaves(logicNull($request["noticias.palavras_chaves"]));
			$noticias->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$noticias->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$noticias->setUsuario($request["noticias.usuario"]);
			$noticias->setSituacao_registro($request["noticias.situacao_registro"]);
			$noticias->setTipo_noticia($request["noticias.tipo_noticia"]);
			
			$resultDao = $daoFactory->getNoticiasDao()->create($noticias);

			if ($resultDao) {
				$daoFactory->commit();
				$response["message"] = "success";
			} else {							
				$daoFactory->rollback();
				$response["message"] = "error";
			}

			$daoFactory->close();
		} else {
			$response["message"] = "error";
		}
		
		echo $view->json($response);
	}
	
	/*
	 * Read
	 */
	else if ($method == "api-read") {
		enableCORS();
		
		if (isset($_POST["request"])) {
			$request = json_decode($_POST["request"], true);
			
			$limit = "noticias.id DESC LIMIT " . 
					(($request[0]["page"] * $request[0]["pageSize"]) - 
					$request[0]["pageSize"]) . ", " . $request[0]["pageSize"];	
		}
		
		$daoFactory->beginTransaction();
		$noticias = $daoFactory->getNoticiasDao()->read("", $limit, false);
		$daoFactory->close();
		
		echo $view->json($noticias);
	}
	
	/*
	 * Update
	 */
	else if ($method == "api-update") {	
		enableCORS();
		if (isset($_POST["request"])) {
			$request = json_decode($_POST["request"], true);
			// $request[0]["@_PARAM"] = $daoFactory->prepare($request[0]["@_PARAM"]); // Prepare with sql injection.
			
			$noticias = new model\Noticias();
			$noticias->setId($request["noticias.id"]);
			$noticias->setNoticia(logicNull($request["noticias.noticia"]));
			
			$where = "noticias.id = " . $request["noticias.id"];
			
			$daoFactory->beginTransaction();
			$noticiasDao = $daoFactory->getNoticiasDao()->read($where, "", false);
			$daoFactory->close();
				
			if (isset($_FILES["upload"])) {
				if ($noticiasDao[0]["noticias.foto"] != "") {	
					unlink($_DOCUMENT_ROOT . "/res/img/ldpi/" . $noticiasDao[0]["noticias.foto"]);
					unlink($_DOCUMENT_ROOT . "/res/img/mdpi/" . $noticiasDao[0]["noticias.foto"]);
					unlink($_DOCUMENT_ROOT . "/res/img/hdpi/" . $noticiasDao[0]["noticias.foto"]);
				}
				
				$upload = new getz\Upload($_FILES["upload"], 1200);
				$noticias->setFoto($upload->getName());
			} else {
				$noticias->setFoto($noticiasDao[0]["noticias.foto"]);
			}
			$noticias->setLegenda_foto(logicNull($request["noticias.legenda_foto"]));
			$noticias->setResumo(logicNull($request["noticias.resumo"]));
			$noticias->setConteudo(logicNull($request["noticias.conteudo"]));
			$noticias->setPalavras_chaves(logicNull($request["noticias.palavras_chaves"]));
			$noticias->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$noticias->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$noticias->setUsuario($request["noticias.usuario"]);
			$noticias->setSituacao_registro($request["noticias.situacao_registro"]);
			$noticias->setTipo_noticia($request["noticias.tipo_noticia"]);
			
			$daoFactory->beginTransaction();
			$resultDao = $daoFactory->getNoticiasDao()->update($noticias);

			if ($resultDao) {
				$daoFactory->commit();
				$response["message"] = "success";
			} else {							
				$daoFactory->rollback();
				$response["message"] = "error";
			}

			$daoFactory->close();
		} else {
			$response["message"] = "error";
		}
		
		echo $view->json($response);
	}
	
	/* 
	 * Delete
	 */
	else if ($method == "api-delete") {
		enableCORS();
		if (isset($_POST["request"])) {
			$request = json_decode($_POST["request"], true);
			$request["noticias.id"] = $daoFactory->prepare($request["noticias.id"]); // Prepare with sql injection.
				
			$result = true;
			$lines = explode("<gz>", $request["noticias.id"]);

			$daoFactory->beginTransaction();

			for ($i = 0; $i < sizeof($lines); $i++) {
				$where = "noticias.id = " . $lines[$i];
				
				$noticiasDao = $daoFactory->getNoticiasDao()->read($where, "", false);
				
				if ($noticiasDao[0]["noticias.foto"] != "") {	
					unlink($_DOCUMENT_ROOT . "/res/img/ldpi/" . $noticiasDao[0]["noticias.foto"]);
					unlink($_DOCUMENT_ROOT . "/res/img/mdpi/" . $noticiasDao[0]["noticias.foto"]);
					unlink($_DOCUMENT_ROOT . "/res/img/hdpi/" . $noticiasDao[0]["noticias.foto"]);
				}
				
				$resultDao = $daoFactory->getNoticiasDao()->delete($where);
				$result = !$result ? false : (!$resultDao ? false : true);
			}

			if ($result) {
				$daoFactory->commit();
				$response["message"] = "success";
			} else {							
				$daoFactory->rollback();
				$response["message"] = "error";
			}

			$daoFactory->close();
		} else {
			$response["message"] = "error";
		} 

		echo $view->json($response);
	}
	
	else if ($method == "changeOrder") {		
		$result = true;
		$daoFactory->beginTransaction();
		$call = $daoFactory->getNoticiasDao()->read("noticias.id = " . $form[0], "", false);
		$answer = $daoFactory->getNoticiasDao()->read("noticias.id = " . $form[1], "", false);
		$noticiasDao = $daoFactory->getNoticiasDao()->read("noticias.ordem >= " . $answer[0]["noticias.ordem"], "", false);
		if (is_array($noticiasDao) && sizeof($noticiasDao) > 0) {
			for ($x = 0; $x < sizeof($noticiasDao); $x++) {
				$noticias = new model\Noticias();
				$noticias->setId($noticiasDao[$x]["noticias.id"]);
				$noticias->setNoticia(logicNull($noticiasDao[$x]["noticias.noticia"]));
			
			if (isset($_FILES["upload"])) {
				if ($noticiasDao[$x]["noticias.foto"] != "") {	
					unlink($_DOCUMENT_ROOT . "/res/img/ldpi/" . $noticiasDao[$x]["noticias.foto"]);
					unlink($_DOCUMENT_ROOT . "/res/img/mdpi/" . $noticiasDao[$x]["noticias.foto"]);
					unlink($_DOCUMENT_ROOT . "/res/img/hdpi/" . $noticiasDao[$x]["noticias.foto"]);
				}
				
				$upload = new getz\Upload($_FILES["upload"], 1200);
				$noticias->setFoto($upload->getName());
			} else {
				$noticias->setFoto($noticiasDao[$x]["noticias.foto"]);
			}
			
			$noticias->setLegenda_foto(logicNull($noticiasDao[$x]["noticias.legenda_foto"]));
			$noticias->setResumo(logicNull($noticiasDao[$x]["noticias.resumo"]));
			$noticias->setConteudo(logicNull($noticiasDao[$x]["noticias.conteudo"]));
			$noticias->setPalavras_chaves(logicNull($noticiasDao[$x]["noticias.palavras_chaves"]));
			$noticias->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$noticias->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$noticias->setUsuario($noticiasDao[$x]["noticias.usuario"]);
			$noticias->setSituacao_registro($noticiasDao[$x]["noticias.situacao_registro"]);
			$noticias->setTipo_noticia($noticiasDao[$x]["noticias.tipo_noticia"]);
			
				$resultDao = $daoFactory->getNoticiasDao()->update($noticias);			
				$result = !$result ? false : (!$resultDao ? false : true);
			}
			$noticias = new model\Noticias();
			$noticias->setId($call[0]["noticias.id"]);
			$noticias->setNoticia(logicNull($call[0]["noticias.noticia"]));
			
			if (isset($_FILES["upload"])) {
				if ($call[0]["noticias.foto"] != "") {	
					unlink($_DOCUMENT_ROOT . "/res/img/ldpi/" . $call[0]["noticias.foto"]);
					unlink($_DOCUMENT_ROOT . "/res/img/mdpi/" . $call[0]["noticias.foto"]);
					unlink($_DOCUMENT_ROOT . "/res/img/hdpi/" . $call[0]["noticias.foto"]);
				}
				
				$upload = new getz\Upload($_FILES["upload"], 1200);
				$noticias->setFoto($upload->getName());
			} else {
				if ($call[0]["noticias.foto"] != "") {	
					$noticias->setFoto($call[0]["noticias.foto"]);
				} else {
					$noticias->setFoto("");
				}
			}
			
			$noticias->setLegenda_foto(logicNull($call[0]["noticias.legenda_foto"]));
			$noticias->setResumo(logicNull($call[0]["noticias.resumo"]));
			$noticias->setConteudo(logicNull($call[0]["noticias.conteudo"]));
			$noticias->setPalavras_chaves(logicNull($call[0]["noticias.palavras_chaves"]));
			$noticias->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$noticias->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$noticias->setUsuario($call[0]["noticias.usuario"]);
			$noticias->setSituacao_registro($call[0]["noticias.situacao_registro"]);
			$noticias->setTipo_noticia($call[0]["noticias.tipo_noticia"]);
			
			$resultDao = $daoFactory->getNoticiasDao()->update($noticias);			
			$result = !$result ? false : (!$resultDao ? false : true);
		}
		if ($result) {
			$daoFactory->commit();
			$response[0]["message"] = "success";
		} else {							
			$daoFactory->rollback();
			$response[0]["message"] = "error";
		}
		$daoFactory->close();
		echo $darth->json($response);
	}
	
	/**************************************************
	 * System
	 **************************************************/	
	
	else {
		if (!getActiveSession($_ROOT . $_MODULE)) 
			echo "<script>goTo(\"/login/1\");</script>";
		else {
			/*
			 * Create
			 */
			if ($method == "stateCreate") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					$daoFactory->beginTransaction();
					$response["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
					$response["usuarios"] = $daoFactory->getUsuariosDao()->read("", "usuarios.id ASC", false);
					$response["situacoes_registros"] = $daoFactory->getSituacoes_registrosDao()->read("", "situacoes_registros.id ASC", false);
					$response["tipos_noticias"] = $daoFactory->getTipos_noticiasDao()->read("", "tipos_noticias.id ASC", false);
					$daoFactory->close();

					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.html", getMenu($daoFactory, $_USER, $screen));
					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/noticias/noticiasCRT.html", $response);
				}
			}

			/*
			 * Read
			 */
			else if ($method == "stateRead" || $method == "stateReadAll") {
				if ($method == "stateReadAll") {
					$method = "stateRead";
				}
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					$daoFactory->beginTransaction();
					$response["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
					$response["noticias"] = $daoFactory->getNoticiasDao()->read($where, $limit, true);
					if (!is_array($response["noticias"])) {
						$response["data_not_found"][0]["value"] = "<p>Não possui registro.</p>";
					}
					$daoFactory->close();

					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.html", getMenu($daoFactory, $_USER, $screen));
					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/noticias/noticiasRD.html", $response);
				}
			}

			/*
			 * Update
			 */
			else if ($method == "stateUpdate") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					$daoFactory->beginTransaction();
					$response["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
					$response["noticias"] = $daoFactory->getNoticiasDao()->read($where, "", true);
					$response["noticias"][0]["noticias.usuarios"] = $daoFactory->getUsuariosDao()->read("", "usuarios.id ASC", false);
					for ($x = 0; $x < sizeof($response["noticias"][0]["noticias.usuarios"]); $x++) {
						if ($response["noticias"][0]["noticias.usuarios"][$x]["usuarios.id"] == 
								$response["noticias"][0]["noticias.usuario"]) {
							$response["noticias"][0]["noticias.usuarios"][$x]["usuarios.selected"] = "selected";
						}
					}
					$response["noticias"][0]["noticias.situacoes_registros"] = $daoFactory->getSituacoes_registrosDao()->read("", "situacoes_registros.id ASC", false);
					for ($x = 0; $x < sizeof($response["noticias"][0]["noticias.situacoes_registros"]); $x++) {
						if ($response["noticias"][0]["noticias.situacoes_registros"][$x]["situacoes_registros.id"] == 
								$response["noticias"][0]["noticias.situacao_registro"]) {
							$response["noticias"][0]["noticias.situacoes_registros"][$x]["situacoes_registros.selected"] = "selected";
						}
					}
					$response["noticias"][0]["noticias.tipos_noticias"] = $daoFactory->getTipos_noticiasDao()->read("", "tipos_noticias.id ASC", false);
					for ($x = 0; $x < sizeof($response["noticias"][0]["noticias.tipos_noticias"]); $x++) {
						if ($response["noticias"][0]["noticias.tipos_noticias"][$x]["tipos_noticias.id"] == 
								$response["noticias"][0]["noticias.tipo_noticia"]) {
							$response["noticias"][0]["noticias.tipos_noticias"][$x]["tipos_noticias.selected"] = "selected";
						}
					}
					$daoFactory->close();

					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.html", getMenu($daoFactory, $_USER, $screen));
					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/noticias/noticiasUPD.html", $response);
				}
			}

			/*
			 * Called
			 */
			else if ($method == "stateCalled" || $method == "stateCalledAll") {
				if ($method == "stateCalledAll") {
					$method = "stateCalled";
				}
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					/*
					 * Insert your foreign key here
					 */
					if ($where != "")
						$where .= " AND noticias.@_FOREIGN_KEY = " . $base;
					else 
						$where = "noticias.@_FOREIGN_KEY = " . $base;
						
					$daoFactory->beginTransaction();
					$response["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
					$response["noticias"] = $daoFactory->getNoticiasDao()->read($where, $limit, true);
					if (!is_array($response["noticias"])) {
						$response["data_not_found"][0]["value"] = "<p>Não possui registro.</p>";
					}
					$daoFactory->close();

					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.html", getMenu($daoFactory, $_USER, $screen));
					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/noticias/noticiasCLL.html", $response);
				}
			}

			/*
			 * Screen
			 */
			else if ($method == "screen") {
				if ($base != "") {
					$arrBase = explode("<gz>", $base);
					
					if (sizeof($arrBase) > 1) {
						if ($where != "")
							$where .= " AND noticias.@_FOREIGN_KEY = " . $arrBase[1];
						else
							$where = "noticias.@_FOREIGN_KEY = " . $arrBase[1];
					}
				}
				
				$limit = "noticias.id DESC LIMIT " . (($position * 5) - 5) . ", 5";

				$daoFactory->beginTransaction();
				$response["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
				$response["noticias"] = $daoFactory->getNoticiasDao()->read($where, $limit, true);
				$daoFactory->close();

				echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/noticias/noticiasSCR.html", $response) . 
						"<size>" . (is_array($response["noticias"]) ? $response["noticias"][0]["noticias.size"] : 0) . "<theme>455a64";
			}

			/*
			 * Screen handler
			 */
			else if ($method == "screenHandler") {	
				$where = "";

				// Get value from combo
				$cmb = explode("<gz>", $search);

				if ($cmb[1] != "")
					$where = "noticias.id = " . $cmb[1];

				$daoFactory->beginTransaction();
				$response["noticias"] = $daoFactory->getNoticiasDao()->comboScr($where);
				$daoFactory->close();

				echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/noticias/noticiasCMB.html", $response);
			}

			/*
			 * Create
			 */
			else if ($method == "create") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method)) {
					$response["message"] = "permission";
					
					echo $view->json($response);
				} else {
					$noticias = new model\Noticias();
					$noticias->setNoticia(logicNull($form[0]));
					
					/*
					 * Upload File
					 */
					if (isset($_FILES["upload"])) {
						$upload = new getz\Upload($_FILES["upload"], 1200);
						$noticias->setFoto($upload->getName());
					} else 
						$noticias->setFoto("");
						
					$noticias->setLegenda_foto(logicNull($form[1]));
					$noticias->setResumo(logicNull($form[2]));
					$noticias->setConteudo(logicNull($form[3]));
					$noticias->setPalavras_chaves(logicNull($form[4]));
					$noticias->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					$noticias->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					$noticias->setUsuario($form[5]);
					$noticias->setSituacao_registro($form[6]);
					$noticias->setTipo_noticia($form[7]);
					
					$daoFactory->beginTransaction();
					$resultDao = $daoFactory->getNoticiasDao()->create($noticias);

					if ($resultDao) {
						$daoFactory->commit();
						$response["message"] = "success";				
					} else {							
						$daoFactory->rollback();
						$response["message"] = "error";
					}

					$daoFactory->close();

					echo $view->json($response);
				}
			}

			/*
			 * Action update
			 */
			else if ($method == "update") {	
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method)) {
					$response["message"] = "permission";
					
					echo $view->json($response);
				} else {
					$noticias = new model\Noticias();
					$noticias->setId($code);
					$noticias->setNoticia(logicNull($form[0]));
					
					/*
					 * Get object
					 */
					$where = "noticias.id = " . $code;
					
					$daoFactory->beginTransaction();
					$noticiasDao = $daoFactory->getNoticiasDao()->read($where, "", false);
					$daoFactory->close();
						
					/*
					 * Upload File
					 */
					if (isset($_FILES["upload"])) {
						if ($noticiasDao[0]["noticias.foto"] != "") {	
							/*
							 * Unlink
							 */
							unlink($_DOCUMENT_ROOT . "/res/img/ldpi/" . $noticiasDao[0]["noticias.foto"]); 
							unlink($_DOCUMENT_ROOT . "/res/img/mdpi/" . $noticiasDao[0]["noticias.foto"]);
							unlink($_DOCUMENT_ROOT . "/res/img/hdpi/" . $noticiasDao[0]["noticias.foto"]);
						}
						
						$upload = new getz\Upload($_FILES["upload"], 1200);
						$noticias->setFoto($upload->getName());
					} else {
						$noticias->setFoto($noticiasDao[0]["noticias.foto"]);
					}
					$noticias->setLegenda_foto(logicNull($form[1]));
					$noticias->setResumo(logicNull($form[2]));
					$noticias->setConteudo(logicNull($form[3]));
					$noticias->setPalavras_chaves(logicNull($form[4]));
					$noticias->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					$noticias->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					$noticias->setUsuario($form[5]);
					$noticias->setSituacao_registro($form[6]);
					$noticias->setTipo_noticia($form[7]);
					
					$daoFactory->beginTransaction();
					$resultDao = $daoFactory->getNoticiasDao()->update($noticias);

					if ($resultDao) {
						$daoFactory->commit();
						$response["message"] = "success";
					} else {							
						$daoFactory->rollback();
						$response["message"] = "error";
					}

					$daoFactory->close();

					echo $view->json($response);
				}
			}
			
			/* 
			 * Action delete
			 */
			else if ($method == "delete") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method)) {
					$response["message"] = "permission";
					
					echo $view->json($response);
				} else {
					$result = true;
					$lines = explode("<gz>", $code);

					$daoFactory->beginTransaction();

					for ($i = 1; $i < sizeof($lines); $i++) {
						$where = "noticias.id = " . $lines[$i];
						
						/*
						 * Unlink
						 */
						$noticiasDao = $daoFactory->getNoticiasDao()->read($where, "", false);
						
						if ($noticiasDao[0]["noticias.foto"] != "") {	
							unlink($_DOCUMENT_ROOT . "/res/img/ldpi/" . $noticiasDao[0]["noticias.foto"]);
							unlink($_DOCUMENT_ROOT . "/res/img/mdpi/" . $noticiasDao[0]["noticias.foto"]);
							unlink($_DOCUMENT_ROOT . "/res/img/hdpi/" . $noticiasDao[0]["noticias.foto"]);
						}
						
						$resultDao = $daoFactory->getNoticiasDao()->delete($where);
						$result = !$result ? false : (!$resultDao ? false : true);
					}

					if ($result) {
						$daoFactory->commit();
						$response["message"] = "success";
					} else {							
						$daoFactory->rollback();
						$response["message"] = "error";
					}

					$daoFactory->close();

					echo $view->json($response);	
				}
			}
		}
	}

?>