<?php

	/**
	 * Generated by Getz Framework
	 *
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz
	 */
	 
	use lib\getz;
	use src\logic;	 
	use src\model;	 
	
	require_once($_DOCUMENT_ROOT . "/lib/getz/Activator.php");
	
	/*
	 * Filters
	 */
	$where = "";
	
	if ($search != "")
		$where = "situacoes_contatos.situacao_contato LIKE \"%" . $search . "%\"";	
		
	if ($code != "")
		$where = "situacoes_contatos.id = " . $code;
	
	if (isset($_GET["friendly"]))
		$where = "situacoes_contatos.situacao_contato = \"" . removeLine($_GET["friendly"]) . "\"";	
		
	$limit = "";	
	
	if ($order != "") {
		$o = explode("<gz>", $order);
		if ($method == "stateReadAll" || $method == "stateCalledAll") {
			$limit = $o[0] . " " . $o[1];
		} else {
			$limit = $o[0] . " " . $o[1] . " LIMIT " . 
					(($position * $itensPerPage) - $itensPerPage) . ", " . $itensPerPage;
		}		
	} else {
		if ($method == "stateReadAll" || $method == "stateCalledAll") {
			$limit = "situacoes_contatos.ordem ASC";	
		} else {
			if ($position > 0 && $itensPerPage > 0) {
				$limit = "situacoes_contatos.id DESC LIMIT " . 
						(($position * $itensPerPage) - $itensPerPage) . ", " . $itensPerPage;	
			}
		}
	}
	
	/**************************************************
	 * Webpage
	 **************************************************/		
	
	/*
	 * Page
	 */
	if ($method == "page") {
		/*
		 * SEO
		 */
		$view->setTitle(ucfirst($screen));
		$view->setDescription("");
		$view->setKeywords("");
		
		$daoFactory->beginTransaction();
		$response["situacoes_contatos"] = $daoFactory->getSituacoes_contatosDao()->read($where, $limit, true);
		$daoFactory->close();
		
		if (isset($_GET["friendly"]))
			$view->setTitle($response["situacoes_contatos"][0]["situacoes_contatos.situacao_contato"]);

		echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/header.html", $response);
		
		echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . 
				(isset($_GET["friendly"]) ? "/html/situacoes_contatos.html" : "/html/situacoes_contatos.html"), $response);
		
		echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/footer.html", $response);
	}
	
	/**************************************************
	 * Webservice
	 **************************************************/	

	/*
	 * Create
	 */
	else if ($method == "api-create") {
		enableCORS();
		if (isset($_POST["request"])) {
			$request = json_decode($_POST["request"], true);
			// $request[0]["@_PARAM"] = $daoFactory->prepare($request[0]["@_PARAM"]); // Prepare with sql injection.

			$daoFactory->beginTransaction();
			$situacoes_contatos = new model\Situacoes_contatos();
			$situacoes_contatos->setSituacao_contato(logicNull($request["situacoes_contatos.situacao_contato"]));
			$situacoes_contatos->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$situacoes_contatos->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$situacoes_contatos->setCor($request["situacoes_contatos.cor"]);
			
			$resultDao = $daoFactory->getSituacoes_contatosDao()->create($situacoes_contatos);

			if ($resultDao) {
				$daoFactory->commit();
				$response["message"] = "success";
			} else {							
				$daoFactory->rollback();
				$response["message"] = "error";
			}

			$daoFactory->close();
		} else {
			$response["message"] = "error";
		}
		
		echo $view->json($response);
	}
	
	/*
	 * Read
	 */
	else if ($method == "api-read") {
		enableCORS();
		
		if (isset($_POST["request"])) {
			$request = json_decode($_POST["request"], true);
			
			$limit = "situacoes_contatos.id DESC LIMIT " . 
					(($request[0]["page"] * $request[0]["pageSize"]) - 
					$request[0]["pageSize"]) . ", " . $request[0]["pageSize"];	
		}
		
		$daoFactory->beginTransaction();
		$situacoes_contatos = $daoFactory->getSituacoes_contatosDao()->read("", $limit, false);
		$daoFactory->close();
		
		echo $view->json($situacoes_contatos);
	}
	
	/*
	 * Update
	 */
	else if ($method == "api-update") {	
		enableCORS();
		if (isset($_POST["request"])) {
			$request = json_decode($_POST["request"], true);
			// $request[0]["@_PARAM"] = $daoFactory->prepare($request[0]["@_PARAM"]); // Prepare with sql injection.
			
			$situacoes_contatos = new model\Situacoes_contatos();
			$situacoes_contatos->setId($request["situacoes_contatos.id"]);
			$situacoes_contatos->setSituacao_contato(logicNull($request["situacoes_contatos.situacao_contato"]));
			$situacoes_contatos->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$situacoes_contatos->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$situacoes_contatos->setCor($request["situacoes_contatos.cor"]);
			
			$daoFactory->beginTransaction();
			$resultDao = $daoFactory->getSituacoes_contatosDao()->update($situacoes_contatos);

			if ($resultDao) {
				$daoFactory->commit();
				$response["message"] = "success";
			} else {							
				$daoFactory->rollback();
				$response["message"] = "error";
			}

			$daoFactory->close();
		} else {
			$response["message"] = "error";
		}
		
		echo $view->json($response);
	}
	
	/* 
	 * Delete
	 */
	else if ($method == "api-delete") {
		enableCORS();
		if (isset($_POST["request"])) {
			$request = json_decode($_POST["request"], true);
			$request["situacoes_contatos.id"] = $daoFactory->prepare($request["situacoes_contatos.id"]); // Prepare with sql injection.
				
			$result = true;
			$lines = explode("<gz>", $request["situacoes_contatos.id"]);

			$daoFactory->beginTransaction();

			for ($i = 0; $i < sizeof($lines); $i++) {
				$where = "situacoes_contatos.id = " . $lines[$i];
				
				$resultDao = $daoFactory->getSituacoes_contatosDao()->delete($where);
				$result = !$result ? false : (!$resultDao ? false : true);
			}

			if ($result) {
				$daoFactory->commit();
				$response["message"] = "success";
			} else {							
				$daoFactory->rollback();
				$response["message"] = "error";
			}

			$daoFactory->close();
		} else {
			$response["message"] = "error";
		} 

		echo $view->json($response);
	}
	
	else if ($method == "changeOrder") {		
		$result = true;
		$daoFactory->beginTransaction();
		$call = $daoFactory->getSituacoes_contatosDao()->read("situacoes_contatos.id = " . $form[0], "", false);
		$answer = $daoFactory->getSituacoes_contatosDao()->read("situacoes_contatos.id = " . $form[1], "", false);
		$situacoes_contatosDao = $daoFactory->getSituacoes_contatosDao()->read("situacoes_contatos.ordem >= " . $answer[0]["situacoes_contatos.ordem"], "", false);
		if (is_array($situacoes_contatosDao) && sizeof($situacoes_contatosDao) > 0) {
			for ($x = 0; $x < sizeof($situacoes_contatosDao); $x++) {
				$situacoes_contatos = new model\Situacoes_contatos();
				$situacoes_contatos->setId($situacoes_contatosDao[$x]["situacoes_contatos.id"]);
				$situacoes_contatos->setSituacao_contato(logicNull($situacoes_contatosDao[$x]["situacoes_contatos.situacao_contato"]));
			$situacoes_contatos->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$situacoes_contatos->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$situacoes_contatos->setCor($situacoes_contatosDao[$x]["situacoes_contatos.cor"]);
			
				$resultDao = $daoFactory->getSituacoes_contatosDao()->update($situacoes_contatos);			
				$result = !$result ? false : (!$resultDao ? false : true);
			}
			$situacoes_contatos = new model\Situacoes_contatos();
			$situacoes_contatos->setId($call[0]["situacoes_contatos.id"]);
			$situacoes_contatos->setSituacao_contato(logicNull($call[0]["situacoes_contatos.situacao_contato"]));
			$situacoes_contatos->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$situacoes_contatos->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$situacoes_contatos->setCor($call[0]["situacoes_contatos.cor"]);
			
			$resultDao = $daoFactory->getSituacoes_contatosDao()->update($situacoes_contatos);			
			$result = !$result ? false : (!$resultDao ? false : true);
		}
		if ($result) {
			$daoFactory->commit();
			$response[0]["message"] = "success";
		} else {							
			$daoFactory->rollback();
			$response[0]["message"] = "error";
		}
		$daoFactory->close();
		echo $darth->json($response);
	}
	
	/**************************************************
	 * System
	 **************************************************/	
	
	else {
		if (!getActiveSession($_ROOT . $_MODULE)) 
			echo "<script>goTo(\"/login/1\");</script>";
		else {
			/*
			 * Create
			 */
			if ($method == "stateCreate") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					$daoFactory->beginTransaction();
					$response["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
					$response["cores"] = $daoFactory->getCoresDao()->read("cores.tipo_cor = 1", "cores.id ASC", false);
					$daoFactory->close();

					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.html", getMenu($daoFactory, $_USER, $screen));
					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/situacoes_contatos/situacoes_contatosCRT.html", $response);
				}
			}

			/*
			 * Read
			 */
			else if ($method == "stateRead" || $method == "stateReadAll") {
				if ($method == "stateReadAll") {
					$method = "stateRead";
				}
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					$daoFactory->beginTransaction();
					$response["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
					$response["situacoes_contatos"] = $daoFactory->getSituacoes_contatosDao()->read($where, $limit, true);
					if (!is_array($response["situacoes_contatos"])) {
						$response["data_not_found"][0]["value"] = "<p>Não possui registro.</p>";
					}
					$daoFactory->close();

					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.html", getMenu($daoFactory, $_USER, $screen));
					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/situacoes_contatos/situacoes_contatosRD.html", $response);
				}
			}

			/*
			 * Update
			 */
			else if ($method == "stateUpdate") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					$daoFactory->beginTransaction();
					$response["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
					$response["situacoes_contatos"] = $daoFactory->getSituacoes_contatosDao()->read($where, "", true);
					$response["situacoes_contatos"][0]["situacoes_contatos.cores"] = $daoFactory->getCoresDao()->read("cores.tipo_cor = 1", "cores.id ASC", false);
					for ($x = 0; $x < sizeof($response["situacoes_contatos"][0]["situacoes_contatos.cores"]); $x++) {
						if ($response["situacoes_contatos"][0]["situacoes_contatos.cores"][$x]["cores.id"] == 
								$response["situacoes_contatos"][0]["situacoes_contatos.cor"]) {
							$response["situacoes_contatos"][0]["situacoes_contatos.cores"][$x]["cores.selected"] = "selected";
						}
					}
					$daoFactory->close();

					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.html", getMenu($daoFactory, $_USER, $screen));
					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/situacoes_contatos/situacoes_contatosUPD.html", $response);
				}
			}

			/*
			 * Called
			 */
			else if ($method == "stateCalled" || $method == "stateCalledAll") {
				if ($method == "stateCalledAll") {
					$method = "stateCalled";
				}
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					/*
					 * Insert your foreign key here
					 */
					if ($where != "")
						$where .= " AND situacoes_contatos.@_FOREIGN_KEY = " . $base;
					else 
						$where = "situacoes_contatos.@_FOREIGN_KEY = " . $base;
						
					$daoFactory->beginTransaction();
					$response["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
					$response["situacoes_contatos"] = $daoFactory->getSituacoes_contatosDao()->read($where, $limit, true);
					if (!is_array($response["situacoes_contatos"])) {
						$response["data_not_found"][0]["value"] = "<p>Não possui registro.</p>";
					}
					$daoFactory->close();

					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.html", getMenu($daoFactory, $_USER, $screen));
					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/situacoes_contatos/situacoes_contatosCLL.html", $response);
				}
			}

			/*
			 * Screen
			 */
			else if ($method == "screen") {
				if ($base != "") {
					$arrBase = explode("<gz>", $base);
					
					if (sizeof($arrBase) > 1) {
						if ($where != "")
							$where .= " AND situacoes_contatos.@_FOREIGN_KEY = " . $arrBase[1];
						else
							$where = "situacoes_contatos.@_FOREIGN_KEY = " . $arrBase[1];
					}
				}
				
				$limit = "situacoes_contatos.id DESC LIMIT " . (($position * 5) - 5) . ", 5";

				$daoFactory->beginTransaction();
				$response["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
				$response["situacoes_contatos"] = $daoFactory->getSituacoes_contatosDao()->read($where, $limit, true);
				$daoFactory->close();

				echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/situacoes_contatos/situacoes_contatosSCR.html", $response) . 
						"<size>" . (is_array($response["situacoes_contatos"]) ? $response["situacoes_contatos"][0]["situacoes_contatos.size"] : 0) . "<theme>455a64";
			}

			/*
			 * Screen handler
			 */
			else if ($method == "screenHandler") {	
				$where = "";

				// Get value from combo
				$cmb = explode("<gz>", $search);

				if ($cmb[1] != "")
					$where = "situacoes_contatos.id = " . $cmb[1];

				$daoFactory->beginTransaction();
				$response["situacoes_contatos"] = $daoFactory->getSituacoes_contatosDao()->comboScr($where);
				$daoFactory->close();

				echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/situacoes_contatos/situacoes_contatosCMB.html", $response);
			}

			/*
			 * Create
			 */
			else if ($method == "create") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method)) {
					$response["message"] = "permission";
					
					echo $view->json($response);
				} else {
					$situacoes_contatos = new model\Situacoes_contatos();
					$situacoes_contatos->setSituacao_contato(logicNull($form[0]));
					$situacoes_contatos->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					$situacoes_contatos->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					$situacoes_contatos->setCor($form[1]);
					
					$daoFactory->beginTransaction();
					$resultDao = $daoFactory->getSituacoes_contatosDao()->create($situacoes_contatos);

					if ($resultDao) {
						$daoFactory->commit();
						$response["message"] = "success";				
					} else {							
						$daoFactory->rollback();
						$response["message"] = "error";
					}

					$daoFactory->close();

					echo $view->json($response);
				}
			}

			/*
			 * Action update
			 */
			else if ($method == "update") {	
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method)) {
					$response["message"] = "permission";
					
					echo $view->json($response);
				} else {
					$situacoes_contatos = new model\Situacoes_contatos();
					$situacoes_contatos->setId($code);
					$situacoes_contatos->setSituacao_contato(logicNull($form[0]));
					$situacoes_contatos->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					$situacoes_contatos->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					$situacoes_contatos->setCor($form[1]);
					
					$daoFactory->beginTransaction();
					$resultDao = $daoFactory->getSituacoes_contatosDao()->update($situacoes_contatos);

					if ($resultDao) {
						$daoFactory->commit();
						$response["message"] = "success";
					} else {							
						$daoFactory->rollback();
						$response["message"] = "error";
					}

					$daoFactory->close();

					echo $view->json($response);
				}
			}
			
			/* 
			 * Action delete
			 */
			else if ($method == "delete") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method)) {
					$response["message"] = "permission";
					
					echo $view->json($response);
				} else {
					$result = true;
					$lines = explode("<gz>", $code);

					$daoFactory->beginTransaction();

					for ($i = 1; $i < sizeof($lines); $i++) {
						$where = "situacoes_contatos.id = " . $lines[$i];
						
						$resultDao = $daoFactory->getSituacoes_contatosDao()->delete($where);
						$result = !$result ? false : (!$resultDao ? false : true);
					}

					if ($result) {
						$daoFactory->commit();
						$response["message"] = "success";
					} else {							
						$daoFactory->rollback();
						$response["message"] = "error";
					}

					$daoFactory->close();

					echo $view->json($response);	
				}
			}
		}
	}

?>