<?php

	/**
	 * Generated by Getz Framework
	 *
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz
	 */
	 
	use lib\getz;
	use src\logic;	 
	use src\model;	 
	
	require_once($_DOCUMENT_ROOT . "/lib/getz/Activator.php");
	
	/*
	 * Filters
	 */
	$where = "";
	
	if ($search != "")
		$where = "slides.slide LIKE \"%" . $search . "%\"";	
		
	if ($code != "")
		$where = "slides.id = " . $code;
	
	if (isset($_GET["friendly"]))
		$where = "slides.slide = \"" . removeLine($_GET["friendly"]) . "\"";	
		
	$limit = "";	
	
	if ($order != "") {
		$o = explode("<gz>", $order);
		if ($method == "stateReadAll" || $method == "stateCalledAll") {
			$limit = $o[0] . " " . $o[1];
		} else {
			$limit = $o[0] . " " . $o[1] . " LIMIT " . 
					(($position * $itensPerPage) - $itensPerPage) . ", " . $itensPerPage;
		}		
	} else {
		if ($method == "stateReadAll" || $method == "stateCalledAll") {
			$limit = "slides.ordem ASC";	
		} else {
			if ($position > 0 && $itensPerPage > 0) {
				$limit = "slides.ordem ASC LIMIT " . 
						(($position * $itensPerPage) - $itensPerPage) . ", " . $itensPerPage;	
			}
		}
	}
	
	/**************************************************
	 * Webpage
	 **************************************************/		
	
	/*
	 * Page
	 */
	if ($method == "page") {
		/*
		 * SEO
		 */
		$view->setTitle(ucfirst($screen));
		$view->setDescription("");
		$view->setKeywords("");
		
		$daoFactory->beginTransaction();
		$response["slides"] = $daoFactory->getSlidesDao()->read($where, $limit, true);
		$daoFactory->close();
		
		if (isset($_GET["friendly"]))
			$view->setTitle($response["slides"][0]["slides.slide"]);

		echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/header.html", $response);
		
		echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . 
				(isset($_GET["friendly"]) ? "/html/slides.html" : "/html/slides.html"), $response);
		
		echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/footer.html", $response);
	}
	
	/**************************************************
	 * Webservice
	 **************************************************/	

	/*
	 * Create
	 */
	else if ($method == "api-create") {
		enableCORS();
		if (isset($_POST["request"])) {
			$request = json_decode($_POST["request"], true);
			// $request[0]["@_PARAM"] = $daoFactory->prepare($request[0]["@_PARAM"]); // Prepare with sql injection.

			$daoFactory->beginTransaction();
			$slides = new model\Slides();
			$slides->setSlide(logicNull($request["slides.slide"]));
			
			if (isset($_FILES["upload"])) {
				$upload = new getz\Upload($_FILES["upload"], 1200);
				$slides->setFoto($upload->getName());
			} else 
				$slides->setFoto("");
				
			$slides->setLink(logicNull($request["slides.link"]));
			
			$slidesDao = $daoFactory->getSlidesDao()->read("", "slides.ordem DESC LIMIT 0, 1", false);
			$slides->setOrdem($slidesDao[0]["slides.ordem"] + 1);
				
			$slides->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$slides->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$slides->setSituacao_registro($request["slides.situacao_registro"]);
			
			$resultDao = $daoFactory->getSlidesDao()->create($slides);

			if ($resultDao) {
				$daoFactory->commit();
				$response["message"] = "success";
			} else {							
				$daoFactory->rollback();
				$response["message"] = "error";
			}

			$daoFactory->close();
		} else {
			$response["message"] = "error";
		}
		
		echo $view->json($response);
	}
	
	/*
	 * Read
	 */
	else if ($method == "api-read") {
		enableCORS();
		
		if (isset($_POST["request"])) {
			$request = json_decode($_POST["request"], true);
			
			$limit = "slides.id DESC LIMIT " . 
					(($request[0]["page"] * $request[0]["pageSize"]) - 
					$request[0]["pageSize"]) . ", " . $request[0]["pageSize"];	
		}
		
		$daoFactory->beginTransaction();
		$slides = $daoFactory->getSlidesDao()->read("", $limit, false);
		$daoFactory->close();
		
		echo $view->json($slides);
	}
	
	/*
	 * Update
	 */
	else if ($method == "api-update") {	
		enableCORS();
		if (isset($_POST["request"])) {
			$request = json_decode($_POST["request"], true);
			// $request[0]["@_PARAM"] = $daoFactory->prepare($request[0]["@_PARAM"]); // Prepare with sql injection.
			
			$slides = new model\Slides();
			$slides->setId($request["slides.id"]);
			$slides->setSlide(logicNull($request["slides.slide"]));
			
			$where = "slides.id = " . $request["slides.id"];
			
			$daoFactory->beginTransaction();
			$slidesDao = $daoFactory->getSlidesDao()->read($where, "", false);
			$daoFactory->close();
				
			if (isset($_FILES["upload"])) {
				if ($slidesDao[0]["slides.foto"] != "") {	
					unlink($_DOCUMENT_ROOT . "/res/img/ldpi/" . $slidesDao[0]["slides.foto"]);
					unlink($_DOCUMENT_ROOT . "/res/img/mdpi/" . $slidesDao[0]["slides.foto"]);
					unlink($_DOCUMENT_ROOT . "/res/img/hdpi/" . $slidesDao[0]["slides.foto"]);
				}
				
				$upload = new getz\Upload($_FILES["upload"], 1200);
				$slides->setFoto($upload->getName());
			} else {
				$slides->setFoto($slidesDao[0]["slides.foto"]);
			}
			$slides->setLink(logicNull($request["slides.link"]));
			
			$where = "slides.id = " . $request["slides.id"];
			
			$daoFactory->beginTransaction();
			$slidesDao = $daoFactory->getSlidesDao()->read($where, "", false);
			$daoFactory->close();

			$slides->setOrdem($slidesDao[0]["slides.ordem"]);
				
			$slides->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$slides->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$slides->setSituacao_registro($request["slides.situacao_registro"]);
			
			$daoFactory->beginTransaction();
			$resultDao = $daoFactory->getSlidesDao()->update($slides);

			if ($resultDao) {
				$daoFactory->commit();
				$response["message"] = "success";
			} else {							
				$daoFactory->rollback();
				$response["message"] = "error";
			}

			$daoFactory->close();
		} else {
			$response["message"] = "error";
		}
		
		echo $view->json($response);
	}
	
	/* 
	 * Delete
	 */
	else if ($method == "api-delete") {
		enableCORS();
		if (isset($_POST["request"])) {
			$request = json_decode($_POST["request"], true);
			$request["slides.id"] = $daoFactory->prepare($request["slides.id"]); // Prepare with sql injection.
				
			$result = true;
			$lines = explode("<gz>", $request["slides.id"]);

			$daoFactory->beginTransaction();

			for ($i = 0; $i < sizeof($lines); $i++) {
				$where = "slides.id = " . $lines[$i];
				
				$slidesDao = $daoFactory->getSlidesDao()->read($where, "", false);
				
				if ($slidesDao[0]["slides.foto"] != "") {	
					unlink($_DOCUMENT_ROOT . "/res/img/ldpi/" . $slidesDao[0]["slides.foto"]);
					unlink($_DOCUMENT_ROOT . "/res/img/mdpi/" . $slidesDao[0]["slides.foto"]);
					unlink($_DOCUMENT_ROOT . "/res/img/hdpi/" . $slidesDao[0]["slides.foto"]);
				}
				
				$resultDao = $daoFactory->getSlidesDao()->delete($where);
				$result = !$result ? false : (!$resultDao ? false : true);
			}

			if ($result) {
				$daoFactory->commit();
				$response["message"] = "success";
			} else {							
				$daoFactory->rollback();
				$response["message"] = "error";
			}

			$daoFactory->close();
		} else {
			$response["message"] = "error";
		} 

		echo $view->json($response);
	}
	
	else if ($method == "changeOrder") {		
		$result = true;
		$daoFactory->beginTransaction();
		$call = $daoFactory->getSlidesDao()->read("slides.id = " . $form[0], "", false);
		$answer = $daoFactory->getSlidesDao()->read("slides.id = " . $form[1], "", false);
		$slidesDao = $daoFactory->getSlidesDao()->read("slides.ordem >= " . $answer[0]["slides.ordem"], "", false);
		if (is_array($slidesDao) && sizeof($slidesDao) > 0) {
			for ($x = 0; $x < sizeof($slidesDao); $x++) {
				$slides = new model\Slides();
				$slides->setId($slidesDao[$x]["slides.id"]);
				$slides->setSlide(logicNull($slidesDao[$x]["slides.slide"]));
			
			if (isset($_FILES["upload"])) {
				if ($slidesDao[$x]["slides.foto"] != "") {	
					unlink($_DOCUMENT_ROOT . "/res/img/ldpi/" . $slidesDao[$x]["slides.foto"]);
					unlink($_DOCUMENT_ROOT . "/res/img/mdpi/" . $slidesDao[$x]["slides.foto"]);
					unlink($_DOCUMENT_ROOT . "/res/img/hdpi/" . $slidesDao[$x]["slides.foto"]);
				}
				
				$upload = new getz\Upload($_FILES["upload"], 1200);
				$slides->setFoto($upload->getName());
			} else {
				$slides->setFoto($slidesDao[$x]["slides.foto"]);
			}
			
			$slides->setLink(logicNull($slidesDao[$x]["slides.link"]));
			
			$slides->setOrdem($slidesDao[$x]["slides.ordem"] + 1);
				
			$slides->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$slides->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$slides->setSituacao_registro($slidesDao[$x]["slides.situacao_registro"]);
			
				$resultDao = $daoFactory->getSlidesDao()->update($slides);			
				$result = !$result ? false : (!$resultDao ? false : true);
			}
			$slides = new model\Slides();
			$slides->setId($call[0]["slides.id"]);
			$slides->setSlide(logicNull($call[0]["slides.slide"]));
			
			if (isset($_FILES["upload"])) {
				if ($call[0]["slides.foto"] != "") {	
					unlink($_DOCUMENT_ROOT . "/res/img/ldpi/" . $call[0]["slides.foto"]);
					unlink($_DOCUMENT_ROOT . "/res/img/mdpi/" . $call[0]["slides.foto"]);
					unlink($_DOCUMENT_ROOT . "/res/img/hdpi/" . $call[0]["slides.foto"]);
				}
				
				$upload = new getz\Upload($_FILES["upload"], 1200);
				$slides->setFoto($upload->getName());
			} else {
				if ($call[0]["slides.foto"] != "") {	
					$slides->setFoto($call[0]["slides.foto"]);
				} else {
					$slides->setFoto("");
				}
			}
			
			$slides->setLink(logicNull($call[0]["slides.link"]));
			
			$slides->setOrdem($answer[0]["slides.ordem"]);
				
			$slides->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$slides->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
			$slides->setSituacao_registro($call[0]["slides.situacao_registro"]);
			
			$resultDao = $daoFactory->getSlidesDao()->update($slides);			
			$result = !$result ? false : (!$resultDao ? false : true);
		}
		if ($result) {
			$daoFactory->commit();
			$response[0]["message"] = "success";
		} else {							
			$daoFactory->rollback();
			$response[0]["message"] = "error";
		}
		$daoFactory->close();
		echo $darth->json($response);
	}
	
	/**************************************************
	 * System
	 **************************************************/	
	
	else {
		if (!getActiveSession($_ROOT . $_MODULE)) 
			echo "<script>goTo(\"/login/1\");</script>";
		else {
			/*
			 * Create
			 */
			if ($method == "stateCreate") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					$daoFactory->beginTransaction();
					$response["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
					$response["situacoes_registros"] = $daoFactory->getSituacoes_registrosDao()->read("", "situacoes_registros.id ASC", false);
					$daoFactory->close();

					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.html", getMenu($daoFactory, $_USER, $screen));
					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/slides/slidesCRT.html", $response);
				}
			}

			/*
			 * Read
			 */
			else if ($method == "stateRead" || $method == "stateReadAll") {
				if ($method == "stateReadAll") {
					$method = "stateRead";
				}
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					$daoFactory->beginTransaction();
					$response["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
					$response["slides"] = $daoFactory->getSlidesDao()->read($where, $limit, true);
					if (!is_array($response["slides"])) {
						$response["data_not_found"][0]["value"] = "<p>Não possui registro.</p>";
					}
					$daoFactory->close();

					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.html", getMenu($daoFactory, $_USER, $screen));
					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/slides/slidesRD.html", $response);
				}
			}

			/*
			 * Update
			 */
			else if ($method == "stateUpdate") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					$daoFactory->beginTransaction();
					$response["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
					$response["slides"] = $daoFactory->getSlidesDao()->read($where, "", true);
					$response["slides"][0]["slides.situacoes_registros"] = $daoFactory->getSituacoes_registrosDao()->read("", "situacoes_registros.id ASC", false);
					for ($x = 0; $x < sizeof($response["slides"][0]["slides.situacoes_registros"]); $x++) {
						if ($response["slides"][0]["slides.situacoes_registros"][$x]["situacoes_registros.id"] == 
								$response["slides"][0]["slides.situacao_registro"]) {
							$response["slides"][0]["slides.situacoes_registros"][$x]["situacoes_registros.selected"] = "selected";
						}
					}
					$daoFactory->close();

					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.html", getMenu($daoFactory, $_USER, $screen));
					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/slides/slidesUPD.html", $response);
				}
			}

			/*
			 * Called
			 */
			else if ($method == "stateCalled" || $method == "stateCalledAll") {
				if ($method == "stateCalledAll") {
					$method = "stateCalled";
				}
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method))
					echo "<script>goTo(\"/login/1\");</script>";	
				else {
					/*
					 * Insert your foreign key here
					 */
					if ($where != "")
						$where .= " AND slides.@_FOREIGN_KEY = " . $base;
					else 
						$where = "slides.@_FOREIGN_KEY = " . $base;
						
					$daoFactory->beginTransaction();
					$response["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
					$response["slides"] = $daoFactory->getSlidesDao()->read($where, $limit, true);
					if (!is_array($response["slides"])) {
						$response["data_not_found"][0]["value"] = "<p>Não possui registro.</p>";
					}
					$daoFactory->close();

					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/menus/menusCST.html", getMenu($daoFactory, $_USER, $screen));
					echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/slides/slidesCLL.html", $response);
				}
			}

			/*
			 * Screen
			 */
			else if ($method == "screen") {
				if ($base != "") {
					$arrBase = explode("<gz>", $base);
					
					if (sizeof($arrBase) > 1) {
						if ($where != "")
							$where .= " AND slides.@_FOREIGN_KEY = " . $arrBase[1];
						else
							$where = "slides.@_FOREIGN_KEY = " . $arrBase[1];
					}
				}
				
				$limit = "slides.id DESC LIMIT " . (($position * 5) - 5) . ", 5";

				$daoFactory->beginTransaction();
				$response["titles"] = $daoFactory->getTelasDao()->read("telas.identificador = \"" . $screen . "\"", "", true);
				$response["slides"] = $daoFactory->getSlidesDao()->read($where, $limit, true);
				$daoFactory->close();

				echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/slides/slidesSCR.html", $response) . 
						"<size>" . (is_array($response["slides"]) ? $response["slides"][0]["slides.size"] : 0) . "<theme>455a64";
			}

			/*
			 * Screen handler
			 */
			else if ($method == "screenHandler") {	
				$where = "";

				// Get value from combo
				$cmb = explode("<gz>", $search);

				if ($cmb[1] != "")
					$where = "slides.id = " . $cmb[1];

				$daoFactory->beginTransaction();
				$response["slides"] = $daoFactory->getSlidesDao()->comboScr($where);
				$daoFactory->close();

				echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/slides/slidesCMB.html", $response);
			}

			/*
			 * Create
			 */
			else if ($method == "create") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method)) {
					$response["message"] = "permission";
					
					echo $view->json($response);
				} else {
					$slides = new model\Slides();
					$slides->setSlide(logicNull($form[0]));
					
					/*
					 * Upload File
					 */
					if (isset($_FILES["upload"])) {
						$upload = new getz\Upload($_FILES["upload"], 1200);
						$slides->setFoto($upload->getName());
					} else 
						$slides->setFoto("");
						
					$slides->setLink(logicNull($form[1]));
					
					$daoFactory->beginTransaction();
					$slidesDao = $daoFactory->getSlidesDao()->read("", "slides.ordem DESC LIMIT 0, 1", false);
					$daoFactory->close();
						
					$slides->setOrdem($slidesDao[0]["slides.ordem"] + 1);
						
					$slides->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					$slides->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					$slides->setSituacao_registro($form[2]);
					
					$daoFactory->beginTransaction();
					$resultDao = $daoFactory->getSlidesDao()->create($slides);

					if ($resultDao) {
						$daoFactory->commit();
						$response["message"] = "success";				
					} else {							
						$daoFactory->rollback();
						$response["message"] = "error";
					}

					$daoFactory->close();

					echo $view->json($response);
				}
			}

			/*
			 * Action update
			 */
			else if ($method == "update") {	
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method)) {
					$response["message"] = "permission";
					
					echo $view->json($response);
				} else {
					$slides = new model\Slides();
					$slides->setId($code);
					$slides->setSlide(logicNull($form[0]));
					
					/*
					 * Get object
					 */
					$where = "slides.id = " . $code;
					
					$daoFactory->beginTransaction();
					$slidesDao = $daoFactory->getSlidesDao()->read($where, "", false);
					$daoFactory->close();
						
					/*
					 * Upload File
					 */
					if (isset($_FILES["upload"])) {
						if ($slidesDao[0]["slides.foto"] != "") {	
							/*
							 * Unlink
							 */
							unlink($_DOCUMENT_ROOT . "/res/img/ldpi/" . $slidesDao[0]["slides.foto"]); 
							unlink($_DOCUMENT_ROOT . "/res/img/mdpi/" . $slidesDao[0]["slides.foto"]);
							unlink($_DOCUMENT_ROOT . "/res/img/hdpi/" . $slidesDao[0]["slides.foto"]);
						}
						
						$upload = new getz\Upload($_FILES["upload"], 1200);
						$slides->setFoto($upload->getName());
					} else {
						$slides->setFoto($slidesDao[0]["slides.foto"]);
					}
					$slides->setLink(logicNull($form[1]));
					
					$where = "slides.id = " . $code;
					
					$daoFactory->beginTransaction();
					$slidesDao = $daoFactory->getSlidesDao()->read($where, "", false);
					$daoFactory->close();
						
					$slides->setOrdem($slidesDao[0]["slides.ordem"]);
						
					$slides->setCadastrado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					$slides->setModificado(date("Y-m-d H:i:s", (time() - 3600 * 3)));
					$slides->setSituacao_registro($form[2]);
					
					$daoFactory->beginTransaction();
					$resultDao = $daoFactory->getSlidesDao()->update($slides);

					if ($resultDao) {
						$daoFactory->commit();
						$response["message"] = "success";
					} else {							
						$daoFactory->rollback();
						$response["message"] = "error";
					}

					$daoFactory->close();

					echo $view->json($response);
				}
			}
			
			/* 
			 * Action delete
			 */
			else if ($method == "delete") {
				if (!getPermission($_ROOT . $_MODULE, $daoFactory, $screen, $method)) {
					$response["message"] = "permission";
					
					echo $view->json($response);
				} else {
					$result = true;
					$lines = explode("<gz>", $code);

					$daoFactory->beginTransaction();

					for ($i = 1; $i < sizeof($lines); $i++) {
						$where = "slides.id = " . $lines[$i];
						
						/*
						 * Unlink
						 */
						$slidesDao = $daoFactory->getSlidesDao()->read($where, "", false);
						
						if ($slidesDao[0]["slides.foto"] != "") {	
							unlink($_DOCUMENT_ROOT . "/res/img/ldpi/" . $slidesDao[0]["slides.foto"]);
							unlink($_DOCUMENT_ROOT . "/res/img/mdpi/" . $slidesDao[0]["slides.foto"]);
							unlink($_DOCUMENT_ROOT . "/res/img/hdpi/" . $slidesDao[0]["slides.foto"]);
						}
						
						$resultDao = $daoFactory->getSlidesDao()->delete($where);
						$result = !$result ? false : (!$resultDao ? false : true);
					}

					if ($result) {
						$daoFactory->commit();
						$response["message"] = "success";
					} else {							
						$daoFactory->rollback();
						$response["message"] = "error";
					}

					$daoFactory->close();

					echo $view->json($response);	
				}
			}
		}
	}

?>